import type { Phase } from "./types";

/**
 * The Six-Phase Programme of the Growing Participator Approach
 * (Greg & Angela Thomson). ~1,500 hours of "special growth participation"
 * from first words to belonging. Curriculum guidance is shown in the
 * grower's home language — exactly like the printed phase guides — while
 * all PRACTICE content stays 100% in the host language.
 */
export const PHASES: Phase[] = [
  {
    id: 1,
    slug: "connecting",
    name: "Connecting",
    tagline: "Special play in the here-and-now",
    hours: 100,
    startHour: 0,
    color: "#7c5cff",
    emoji: "🌱",
    vocabTarget: "~1,000 words understood by ear",
    description:
      "You stand outside a 'wall of noise' — and your nurturer opens a door in it. For one hundred hours you play here-and-now games with objects, picture cards and actions, 100% in the host language. You don't speak yet: you point, act, arrange and laugh. The magic moment comes in minute one: 'This is a man. This is a woman. Where is the woman?' — and you point correctly.",
    principles: [
      "Comprehension before production — listen and respond with your body, not your mouth",
      "No translation, ever. Meaning comes from pictures, objects and actions",
      "Start with two, add one at a time. Ask the newest, weakest words most often",
      "The Iceberg Principle: strong first encounters, many re-encounters. 'I can't remember it' → 'It's in your iceberg'",
      "No writing — your ears must learn before your eyes interfere",
      "Play, not study. The nurturer is a playmate, not a teacher",
    ],
    activities: [
      {
        id: "p1-dozen",
        name: "Rough-and-Ready Dozen",
        description: "The workhorse of Phase 1: a dozen new picture cards or objects per round, learned by pointing.",
        how: "Your nurturer lays out two cards, names them, asks 'Where is the dog?' — you point. One new card is added at a time until twelve are in play, always asked in random order, newest most often.",
        minutes: 15,
        kind: "vocabulary",
        practiceHref: "/practice/vocabulary",
      },
      {
        id: "p1-listen-do",
        name: "Listen & Do (TPR)",
        description: "Total Physical Response: hear a command, perform it with your body.",
        how: "The nurturer commands — 'Stand up! Take the cup! Put the spoon under the plate!' — and you do it. Commands grow from one word to whole chains. Zero speaking required.",
        minutes: 10,
        kind: "listening",
        practiceHref: "/practice/listening",
      },
      {
        id: "p1-make-true",
        name: "Make It True",
        description: "The pointing game in reverse: the nurturer describes the scene, and you change the world to match.",
        how: "'The boy is behind the horse' — so you place the boy doll behind the horse. The nurturer keeps stating things that aren't true yet, and you rearrange dolls, cue cards and toy houses until they are. Later one grower plays 'you' and another plays 'she', and the sentences come alive between you.",
        minutes: 10,
        kind: "listening",
      },
      {
        id: "p1-photos",
        name: "Photos of US in Action",
        description: "Cards made from photos of your own group performing actions — recycled and growing every meeting.",
        how: "'In which photo am I walking? In which photo are you running?' To point right you must decode both the action and the person — I, you, we, she. The deck gains new actions and pairings each meeting, and in 1B you flip it: now you describe the photos yourselves.",
        minutes: 10,
        kind: "listening",
      },
      {
        id: "p1-lexicarry",
        name: "Cartoon Bubbles (Lexicarry)",
        description: "Comic strips with empty speech bubbles carry ~60 social expressions: greetings, thanks, apologies.",
        how: "The nurturer voices what each character is saying — 'Who is saying I'm sorry?' — and you point at the right bubble. Register matters: greeting an elder is not greeting a friend.",
        minutes: 10,
        kind: "culture",
      },
      {
        id: "p1-dictionary",
        name: "Talking Picture Dictionary",
        description: "Every session ends with a numbered audio recording over your picture sheets.",
        how: "At home you 're-live' the day: replay the recording while pointing at each picture. One recording style omits the answer so you can respond physically as self-review.",
        minutes: 10,
        kind: "vocabulary",
        practiceHref: "/practice/repeat",
      },
      {
        id: "p1-power",
        name: "Power Phrases",
        description: "Your eight survival questions: What's this? What's he doing? Who is she? I don't know…",
        how: "These are the power tools that let you fuel your own growth — practiced until automatic, then used in the real world to make anyone your nurturer.",
        minutes: 8,
        kind: "speaking",
        practiceHref: "/practice/speaking",
      },
      {
        id: "p1-sounds",
        name: "Sound Discrimination",
        description: "Ten minutes a day of minimal pairs — hearing the host language's sounds as insiders hear them.",
        how: "Two similar words ('ship'/'sheep'), two cue cards. The nurturer says one; you point. Your ears sharpen long before your mouth follows.",
        minutes: 10,
        kind: "listening",
        practiceHref: "/practice/listening",
      },
      {
        id: "p1-ladder",
        name: "Ladder of Success",
        description: "Phase 1B: your first 300 words climb the iceberg from understanding into speech.",
        how: "Constrained talking games where you name what you already deeply understand. The nurturer never corrects — they 'recast', naturally restating your sentence the right way.",
        minutes: 15,
        kind: "speaking",
        practiceHref: "/practice/speaking",
      },
      {
        id: "p1-infogap",
        name: "Sixteen Pictures (Info-Gap)",
        description: "A barrier game: language alone must identify one card among many.",
        how: "You and a partner hold identical card grids behind a barrier. One describes a card, the other finds it. When words are all you have, words are what grow.",
        minutes: 15,
        kind: "vocabulary",
        practiceHref: "/practice/vocabulary",
      },
      {
        id: "p1-market",
        name: "Marketplace Role-Play",
        description: "Late 1B: a toy marketplace where buying, selling and real bargaining happen entirely in the host language.",
        how: "Each grower runs a stall with goods, a worker puppet and toy money; the nurturer shops first with the full script — greetings, 'Do you have…?', 'How much is it?' — then growers shop from each other. 'I'll give you 100.' 'No, 200.' 'I only have 150.' The haggling is the lesson.",
        minutes: 20,
        kind: "speaking",
      },
    ],
    parts: [
      {
        id: "1a",
        title: "Games for Listening & Responding",
        hours: "Meetings 1–15 · 30–40h",
        focus:
          "Listening only — you never speak. You point, act, arrange and laugh while hundreds of words pour in through picture cards, commands, photos of your own group and comic-strip bubbles.",
        activityIds: [
          "p1-dozen",
          "p1-listen-do",
          "p1-make-true",
          "p1-photos",
          "p1-lexicarry",
          "p1-sounds",
          "p1-dictionary",
        ],
      },
      {
        id: "1b",
        title: "Constrained Two-Way Interaction",
        hours: "Meetings 16–40 · ~60h",
        focus:
          "Two-way at last: your first 300 best-known words climb the iceberg from understanding into careful, constrained speech — ladder games, info-gaps and role-plays, with the nurturer recasting, never correcting.",
        activityIds: ["p1-ladder", "p1-power", "p1-infogap", "p1-market"],
      },
    ],
    milestones: [
      "Point to ~1,000 pictured things, people and actions named by ear",
      "Physically follow multi-part instructions ('put the angry boy next to the small house')",
      "Recognize ~60 social expressions and use greetings in real encounters",
      "Ask the eight Power Phrases to fuel your own growth",
      "Host people feel you have 'a special connection to us'",
    ],
  },
  {
    id: 2,
    slug: "emerging",
    name: "Emerging",
    tagline: "The story-building phase",
    hours: 150,
    startHour: 100,
    color: "#ff8a1e",
    emoji: "🌿",
    vocabTarget: "+1,200 words → ~2,200 total",
    description:
      "You emerge as a person. Host people start catching glimpses of your personality — you're 'probably somebody'. Speech loosens on top of your big listening base, and wordless picture stories become the engine: page by page, the nurturer narrates, you follow, then retell, and finally you draw and tell your own life story.",
    principles: [
      "Speech emerges — it is never forced. Like a child's first words, it comes when the base is ready",
      "Stories carry language: a wordless book page is a here-and-now you can both see",
      "Record everything; clarify the recording, then re-listen at home",
      "Small Talk + One New Fact begins every meeting — real conversation, however small",
    ],
    activities: [
      {
        id: "p2-describe",
        name: "Describe What You See",
        description: "The Monolingual Half Hour: you lead, describing a wordless picture book page in your own emerging words.",
        how: "You say what you can — the nurturer listens, helps, and recasts. It's a team effort, never a performance.",
        minutes: 30,
        kind: "speaking",
        practiceHref: "/practice/speaking",
      },
      {
        id: "p2-storybuild",
        name: "Story-Building with Pictures",
        description: "The nurturer tells a simple story across the pages of a wordless book, a 'busy picture', or a familiar process.",
        how: "Panel by panel: the nurturer narrates and points, you follow and answer questions, then guide the story, then retell parts yourself.",
        minutes: 25,
        kind: "listening",
        practiceHref: "/practice/listening",
      },
      {
        id: "p2-clarify",
        name: "Clarifying the Recording",
        description: "The cornerstone technique: a recorded story is replayed and unpacked together.",
        how: "Pause at every unknown — the nurturer explains in the host language with gestures and pictures. The clarified recording becomes your listening library.",
        minutes: 20,
        kind: "listening",
      },
      {
        id: "p2-wsw",
        name: "Word–Sentence–Word Recordings",
        description: "New vocabulary recorded as word → sentence → word for home re-listening.",
        how: "Each new word is wrapped in a live sentence from today's story, so you re-encounter it in context, not in a list.",
        minutes: 10,
        kind: "vocabulary",
        practiceHref: "/practice/repeat",
      },
      {
        id: "p2-busy",
        name: "Busy Pictures",
        description: "One gloriously detailed scene — many people doing many things — explored together with questions.",
        how: "A market square, a harbour, a packed street: the nurturer names, asks and points while you hunt and answer. When the iceberg's growth slows below pace, a busy picture floods it with fresh words faster than any single story can.",
        minutes: 15,
        kind: "vocabulary",
      },
      {
        id: "p2-process",
        name: "Process Picture Series",
        description: "Familiar processes — making tea, brushing teeth — told step by step across a picture strip.",
        how: "The nurturer narrates each panel in order while you follow, then you act the process out as it's described. A gentle preview of Phase 3's Scripts of Life, one minute of recorded talk at a time.",
        minutes: 15,
        kind: "listening",
      },
      {
        id: "p2-smalltalk",
        name: "Small Talk + One New Fact",
        description: "Every meeting opens with genuine small talk and one new thing about each other's lives.",
        how: "Real relationship is the medium of growth — the conversation is small but it is finally real.",
        minutes: 10,
        kind: "conversation",
      },
      {
        id: "p2-lifestory",
        name: "Draw As You Go: Your Life Story",
        description: "The capstone: you and the nurturer build your own life story with quick drawings and photos.",
        how: "You sketch your childhood home, your family, your journey — and learn to tell your own story, the words you'll use for the rest of your life here.",
        minutes: 30,
        kind: "speaking",
      },
    ],
    parts: [
      {
        id: "2a",
        title: "Loosening the Tongue",
        hours: "~50h",
        focus:
          "You lead: the Monolingual Half Hour. Real small talk opens every meeting, then you describe wordless picture pages in your own emerging words while the nurturer listens, helps and recasts.",
        activityIds: ["p2-smalltalk", "p2-describe"],
      },
      {
        id: "2b",
        title: "Story-Building",
        hours: "~80h",
        focus:
          "The nurturer leads: stories built page by page, recorded, then clarified line by line. The clarified recordings — and their word–sentence–word harvest — become your growing listening library.",
        activityIds: ["p2-storybuild", "p2-clarify", "p2-wsw", "p2-busy", "p2-process"],
      },
      {
        id: "2c",
        title: "Your Own Story",
        hours: "~20h",
        focus:
          "The capstone: drawing as you go, you learn to tell your own life story — the words you'll use to be known for the rest of your life here.",
        activityIds: ["p2-lifestory"],
      },
    ],
    milestones: [
      "Tell a connected sequence — a story — not just single utterances",
      "Understand and retell wordless picture stories",
      "Carry real small talk and share one new fact about your day",
      "Tell your own life story simply, with pictures",
      "Host people sense you are 'probably somebody'",
    ],
  },
  {
    id: 3,
    slug: "knowable",
    name: "Becoming Knowable",
    tagline: "Stuff-we-both-know conversations",
    hours: 250,
    startHour: 250,
    color: "#b8f03c",
    emoji: "🪴",
    vocabTarget: "+2,000 words → ~4,000 total",
    description:
      "Host people can now genuinely get to know you. The engine is shared context: stories you both already know, places you've both seen, things you did together. The nurturer 'massages' your retellings — re-expressing them in better host-language form — and each massaged story becomes new listening material.",
    principles: [
      "Shared knowledge guarantees comprehensibility — talk about stuff you both know",
      "Retell, get massaged, re-record, re-listen: the growth loop of Phase 3",
      "Extended discourse replaces single sentences: narrative, description, explanation",
    ],
    activities: [
      {
        id: "p3-bridge",
        name: "Bridge Story",
        description: "The mainstay: a story known across cultures, heard in host-language form for the first time.",
        how: "You know the plot; you don't know the words. The nurturer tells it, you retell it, the nurturer massages your version, and you re-record the better telling.",
        minutes: 30,
        kind: "speaking",
      },
      {
        id: "p3-script",
        name: "Scripts of Life",
        description: "How things are really done here: making tea, visiting a doctor, getting married.",
        how: "The nurturer narrates a familiar routine step by step. You absorb the insider's script — then describe your home world's version back.",
        minutes: 20,
        kind: "culture",
      },
      {
        id: "p3-cartoon",
        name: "Action Cartoon",
        description: "Wordless video — Tom & Jerry, Mr. Bean — as shared here-and-now.",
        how: "Watch together; the nurturer narrates; you retell. The screen is a picture book that moves.",
        minutes: 20,
        kind: "listening",
        practiceHref: "/practice/listening",
      },
      {
        id: "p3-massage",
        name: "Record-and-Massage Loop",
        description: "The growth loop of Phase 3, made explicit: retell, get re-expressed, re-record, re-listen.",
        how: "You retell today's story onto the recorder; the nurturer re-expresses it in better host-language form — never correcting, just saying it the way an insider would. You re-record the improved telling, and that recording joins your listening library for the week.",
        minutes: 25,
        kind: "speaking",
      },
      {
        id: "p3-shared",
        name: "Shared Experience + Reminiscing",
        description: "Do something together — an outing, cooking — then talk about it again and again.",
        how: "Shared memory is perfect comprehensible input: you were both there. Reminiscing turns experience into language.",
        minutes: 30,
        kind: "conversation",
      },
      {
        id: "p3-prop",
        name: "Discuss-a-Prop",
        description: "Conversations centred on a common object with a story.",
        how: "A teapot, a photo, a tool from the nurturer's home — what is it, who made it, what happened with it. Objects unlock worlds.",
        minutes: 15,
        kind: "conversation",
      },
      {
        id: "p3-flood",
        name: "Input Flooding",
        description: "A grammar pattern flooded through a busy picture or script of life.",
        how: "Not grammar rules — grammar experience. The nurturer saturates natural speech with one form until your ear claims it.",
        minutes: 15,
        kind: "listening",
        practiceHref: "/practice/listening",
      },
      {
        id: "p3-host",
        name: "Host Stories",
        description: "The stories every host person grew up on — and you're about to.",
        how: "Days before the session you soak in a translation of a widely-known host story until the plot is truly yours. Then you hear it in the host language for the first time, negotiating meaning sentence by sentence. Harder than bridge stories — the background knowledge is all theirs — so re-listen to these recordings often.",
        minutes: 30,
        kind: "culture",
      },
    ],
    parts: [
      {
        id: "3a",
        title: "Massaged Stories",
        hours: "~125h",
        focus:
          "Stories whose plots you already own, heard in host form for the first time — told, retold, massaged into better shape and re-recorded. The mainstay: at least half of all session time.",
        activityIds: ["p3-bridge", "p3-script", "p3-cartoon", "p3-massage"],
      },
      {
        id: "3b",
        title: "Stuff We Both Know",
        hours: "~125h",
        focus:
          "Shared context guarantees comprehension: things you did together, objects with histories, grammar floods — and host stories whose plots you pre-loaded at home.",
        activityIds: ["p3-shared", "p3-prop", "p3-flood", "p3-host"],
      },
    ],
    milestones: [
      "Converse on diverse everyday topics like a (simple) adult",
      "Retell a familiar story and absorb its massaged, better form",
      "Understand the scripts of daily host life from the inside",
      "Host people can genuinely get to know you",
    ],
  },
  {
    id: 4,
    slug: "deep-relationships",
    name: "Deep Personal Relationships",
    tagline: "Deep-life conversations",
    hours: 500,
    startHour: 500,
    color: "#ffd234",
    emoji: "🌳",
    vocabTarget: "+3,000 words → ~7,000 total",
    description:
      "The sacred endeavor: heart-to-heart connection. You learn the host world broadly and deeply by learning individual lives broadly and deeply — their histories, their celebrations, their work, their children — and by becoming truly known yourself. A notebook and a recorder are all it takes.",
    principles: [
      "Learn the host world by learning individual lives",
      "Reciprocity: be known as deeply as you seek to know",
      "Record yourself for feedback — your mentor flags where you differ from host norms",
    ],
    activities: [
      {
        id: "p4-lifestory",
        name: "The Life Story Activity",
        description: "The most fruitful Phase 4 activity: exploring your nurturer's life history, chapter by chapter.",
        how: "Guided heart-to-heart interviews — childhood, school, work, love, loss. Recorded, clarified, re-listened.",
        minutes: 45,
        kind: "conversation",
      },
      {
        id: "p4-vocab",
        name: "Vocabulary Recordings",
        description: "Every life-story session ends with its harvest of new words, recorded in living context.",
        how: "Each new word from the word log is captured word–sentence–word, the sentence drawn straight from today's conversation. A notebook and a recorder turn heart-to-hearts into a permanent listening library.",
        minutes: 15,
        kind: "vocabulary",
        practiceHref: "/practice/repeat",
      },
      {
        id: "p4-walkoflife",
        name: "Walk-of-Life Conversations",
        description: "Ethnographic interviewing about how hosts really live: weddings, markets, farming, raising children.",
        how: "You ask structured questions like an anthropologist of the heart, mapping whole cultural domains — the 'Lists of Life'.",
        minutes: 40,
        kind: "culture",
      },
      {
        id: "p4-observe",
        name: "Observe and Describe",
        description: "Detailed observation of host life, then describing what you saw to your mentor.",
        how: "Watch a ceremony, a shop, a kitchen. Describe it; your mentor fills the holes in your seeing and your saying.",
        minutes: 30,
        kind: "speaking",
      },
      {
        id: "p4-feedback",
        name: "Record Yourself for Feedback",
        description: "The nativeness audit: record extended speech, review it with your mentor, re-record improved.",
        how: "Where do your words and ways differ from host norms? Find out kindly, fix it gently, keep your voice.",
        minutes: 25,
        kind: "speaking",
        practiceHref: "/practice/speaking",
      },
      {
        id: "p4-holes",
        name: "Hole-Finding",
        description: "Hunting the gaps in your vocabulary through narration.",
        how: "Narrate a silent film or a busy scene; every word you reach for and miss is a hole — found, filled, recorded.",
        minutes: 20,
        kind: "vocabulary",
        practiceHref: "/practice/vocabulary",
      },
      {
        id: "p4-tworecorder",
        name: "Two-Recorder Technique",
        description: "Your telling on one recorder, your mentor's richer version wrapped around it on a second — compared side by side.",
        how: "Recorder one holds the original story. Play it back with your mentor while recorder two runs, capturing every question, expansion and improved re-expression — fifteen-second questions earning five-minute answers. The layered recordings make fascinating listening for months, even years.",
        minutes: 30,
        kind: "speaking",
      },
    ],
    parts: [
      {
        id: "4-life",
        title: "Life Stories",
        hours: "~200h",
        focus:
          "Your nurturer's life, chapter by chapter — recorded, clarified, re-listened, and harvested for words. Being deeply known starts with deeply knowing.",
        activityIds: ["p4-lifestory", "p4-vocab"],
      },
      {
        id: "4-walks",
        title: "Walks of Life",
        hours: "~200h",
        focus:
          "Ethnography of the heart: mapping whole cultural domains — the Lists of Life — one walk of life at a time, then checking what you saw against what insiders see.",
        activityIds: ["p4-walkoflife", "p4-observe"],
      },
      {
        id: "4-voice",
        title: "Your Voice",
        hours: "~100h",
        focus:
          "The nativeness audit: hearing where your words and ways still differ from host norms, and closing the gap kindly — without losing your own voice.",
        activityIds: ["p4-feedback", "p4-holes", "p4-tworecorder"],
      },
    ],
    milestones: [
      "Hold genuine heart-to-heart conversations about lives and beliefs",
      "Interview hosts about any walk of life with ease",
      "Handle everyday conversation comfortably; tell complex stories with effort",
      "Host people treat you as becoming 'one of us'",
    ],
  },
  {
    id: 5,
    slug: "widening",
    name: "Widening Understanding",
    tagline: "Native-to-native discourse",
    hours: 500,
    startHour: 1000,
    color: "#ff5d5d",
    emoji: "🌲",
    vocabTarget: "→ ~10,000 words recognized",
    description:
      "The final comprehension barrier: host people talking among themselves — fast, idiomatic, layered with culture. With a mentor you work through real native-to-native discourse: radio, films, sermons, jokes, campfire stories. You join your first community of practice and stop being talked down to.",
    principles: [
      "Real speech, not foreigner talk: study what insiders say to insiders",
      "The mentor replaces the nurturer: a guide through authentic discourse",
      "Join a community of practice — growth now lives in groups",
    ],
    activities: [
      {
        id: "p5-record",
        name: "Collect Native-to-Native Recordings",
        description: "Hire two hosts to converse, interview an elder, capture a hot-topic debate.",
        how: "You build a library of authentic insider speech across registers, roles and settings.",
        minutes: 30,
        kind: "listening",
      },
      {
        id: "p5-tensteps",
        name: "The Ten-Step Discourse Session",
        description: "The master template: working through one native-to-native recording with your mentor.",
        how: "Solo pre-listen → clarify line by line → word recordings → re-listen → next-day retelling. Repeat until the wall of noise is a window.",
        minutes: 60,
        kind: "listening",
      },
      {
        id: "p5-retell",
        name: "Next-Day Retelling",
        description: "Each meeting warms up with you retelling yesterday's discourse in your own words.",
        how: "Summarize the stretch you clarified yesterday while your mentor helps you over the gaps. When a whole discourse is finished you retell it end to end — and the retelling itself can be recorded for feedback.",
        minutes: 15,
        kind: "speaking",
      },
      {
        id: "p5-library",
        name: "Listening-Library Review",
        description: "Your clarified discourses live on — solo re-listening keeps every recording earning interest.",
        how: "After each meeting, re-listen to the clarified discourse and its word recordings, then revisit older items on a loose rotation. What was a wall of noise last month is easy listening now — that feeling is the progress meter.",
        minutes: 20,
        kind: "listening",
      },
      {
        id: "p5-media",
        name: "Clarify a Movie or TV Drama",
        description: "Ready-made native discourse: films, series, talk shows.",
        how: "Watch, pause, unpack idioms and cultural references with your mentor — then rewatch and feel it land.",
        minutes: 45,
        kind: "culture",
      },
      {
        id: "p5-epic",
        name: "Epic Storytelling",
        description: "Supercharged talking: long-form narratives told by you.",
        how: "Tell whole epics — your country's history, a novel's plot, your own saga — stretching discourse muscles to native length.",
        minutes: 30,
        kind: "speaking",
        practiceHref: "/practice/speaking",
      },
      {
        id: "p5-community",
        name: "Join a Community of Practice",
        description: "A workplace, club or recurring gathering where you participate weekly.",
        how: "Group talk no longer excludes you. You are inside the room where the language actually lives.",
        minutes: 120,
        kind: "culture",
      },
    ],
    parts: [
      {
        id: "5-collect",
        title: "Collect",
        hours: "ongoing · ~60h",
        focus:
          "Build a library of real insider speech — hired conversations, elders' memories, hot-topic debates, films and series. Speech meant for insiders, not for you.",
        activityIds: ["p5-record", "p5-media"],
      },
      {
        id: "5-clarify",
        title: "Clarify",
        hours: "~320h",
        focus:
          "The Ten-Step engine: one native-to-native discourse at a time, clarified with your mentor, retold the next day, and re-listened until the wall of noise becomes a window.",
        activityIds: ["p5-tensteps", "p5-retell", "p5-library"],
      },
      {
        id: "5-belong",
        title: "Belong",
        hours: "~120h",
        focus:
          "Growth moves into groups: long-form telling of your own, and weekly life inside a community of practice where nobody talks down to you.",
        activityIds: ["p5-epic", "p5-community"],
      },
    ],
    milestones: [
      "Understand hosts talking among themselves at natural speed",
      "Follow films, radio and jokes without mercy-speech",
      "Participate in group settings as a reasonable co-member",
      "Recognize ~10,000 words; switch registers appropriately",
    ],
  },
  {
    id: 6,
    slug: "ever-growing",
    name: "Ever Participating, Ever Growing",
    tagline: "Self-sustaining growth — a life to be lived",
    hours: 500,
    startHour: 1500,
    color: "#3ddc84",
    emoji: "🌍",
    vocabTarget: "Ever-growing — like an insider's",
    description:
      "Life after full-time language learning. You already understand most of what hosts say and do around you, so as long as you keep living among them you keep growing — no designed session required. The real question is no longer 'how do I study?' but 'how much of my life is actually lived in the host world?' Of a week's ~100 waking hours, how many truly belong to host people, in their language? Most newcomers give under 10%. Phase 6 is the quiet revolution that claims more — turning your workplace, home and friendships into host communities of practice. Its shadow is Phase un-6: the comfortable plateau where you believe you're growing but quietly aren't. It's not a language to be learned, but a life to be lived — and now the circle closes: you can become a nurturer for the next grower.",
    principles: [
      "It's not a language to be learned, but a life to be lived — growth flows from how you live, not from sessions",
      "The honest metric: of ~100 waking hours a week, how many are truly lived in the host world? Claim more back from home-life",
      "Beware Phase un-6 — the plateau where you feel you're growing but aren't; a deliberate ~300 hours of special-growth makes 'a new you'",
      "Growing participation is never solo: couples, families, teams and whole workplaces grow together",
      "Any earlier-phase technique can be re-run on any new domain, forever — and the deepest participation is nurturing someone else in",
    ],
    activities: [
      {
        id: "p6-hours",
        name: "Claim Your Host Hours",
        description: "The Phase 6 audit: what share of your ~100 waking hours each week is truly lived in the host world, in their language?",
        how: "Count honestly across work, home, friendships and errands. Then snatch hours back from an expat-bubble home life and give them to host life — not 'to learn the language', but because you belong there.",
        minutes: 20,
        kind: "culture",
      },
      {
        id: "p6-cop",
        name: "Make a Host Community of Practice",
        description: "Turn the opportunity nearest at hand — your workplace, building or circle of friends — into a place where hosts relate to one another, not to a foreigner.",
        how: "Make the host language the working language; bring host members in; expect every expat present to be a growing participator. Stop being the foreigner everyone accommodates and become one more member of the group.",
        minutes: 60,
        kind: "conversation",
      },
      {
        id: "p6-read",
        name: "Read Promiscuously",
        description: "Where reading is a host practice, it is the great accelerator — nearly everyone who reaches near-native read widely.",
        how: "Read on your own; have your nurturer read the same piece; then discuss it together and record the new words. Reading carries you from everyday talk into academic and public language.",
        minutes: 30,
        kind: "literacy",
      },
      {
        id: "p6-needs",
        name: "Needs Analysis",
        description: "Choose your next target discourses deliberately, not by vague ambition.",
        how: "List every communication situation, then score each: how often (0–5) plus how important (0–5) minus how well you already do it (0–10). The high scorers — a toast, a car repair, a salon visit — are where special-growth pays.",
        minutes: 20,
        kind: "culture",
      },
      {
        id: "p6-rare",
        name: "Rare-but-Urgent Discourses",
        description: "Toast-making, getting the car fixed, a hospital visit — infrequent and hard, but high-stakes the moment they arrive.",
        how: "Run the A/B technique: you attempt it in the lead and record; your nurturer massages it for feedback; then the nurturer leads a fresh version for your listening library, and next time you retell it in your own words.",
        minutes: 40,
        kind: "speaking",
      },
      {
        id: "p6-expert",
        name: "Expert Interviewing",
        description: "Phase 4 deep-interviewing taken to professional depth — even content instruction in your field.",
        how: "Interview insiders of your working world — or take a course from a host teacher who shares no language with you — until your work-self speaks the host language too.",
        minutes: 45,
        kind: "conversation",
      },
      {
        id: "p6-remedial",
        name: "Remedial Pickup",
        description: "Any earlier-phase technique, re-run at full power on whatever domain has gone soft.",
        how: "Phase 1 Dirty-Dozen for car parts, a Phase 2 busy-picture, Phase 3 scripts-of-life, world-stories or reminiscing — pick the old tool that fits the gap and aim for ten new words an hour. Even admired 'advanced' speakers meet dozens of new words in a five-minute Cinderella.",
        minutes: 45,
        kind: "vocabulary",
      },
      {
        id: "p6-nurture",
        name: "Become a Nurturer",
        description: "The circle closes: guide a new grower through their own first hundred hours of the wall of noise.",
        how: "You know the wall of noise from both sides now. Nuri unlocks nurturer tools — card decks, session plans, the meeting timer — for any language you've grown into.",
        minutes: 60,
        kind: "conversation",
        practiceHref: "/onboarding",
      },
    ],
    parts: [
      {
        id: "6-live",
        title: "Live It",
        hours: "your whole week",
        focus:
          "The heart of Phase 6: give your host life a fighting chance. Claim a bigger share of your ~100 waking hours and turn workplace, home and friendships into host communities of practice — staying off the Phase un-6 plateau.",
        activityIds: ["p6-hours", "p6-cop", "p6-read"],
      },
      {
        id: "6-target",
        title: "Target",
        hours: "~300h, when you push",
        focus:
          "Optional but powerful: a needs analysis picks your high-value discourses, then the old playbook runs on new ground — rare-but-urgent situations, professional depth, and soft domains revisited at ten new words an hour.",
        activityIds: ["p6-needs", "p6-rare", "p6-expert", "p6-remedial"],
      },
      {
        id: "6-give",
        title: "Give Back",
        hours: "forever",
        focus:
          "The deepest participation: nurturing the next grower through their own first hundred hours of the wall of noise.",
        activityIds: ["p6-nurture"],
      },
    ],
    milestones: [
      "Most of your week's host hours are genuinely lived in the host world, in their language",
      "Growth sustains itself from how you live — designed sessions optional, not required",
      "You can name and escape the Phase un-6 plateau before it sets in",
      "Run any earlier-phase technique on any new domain, for the rest of your life",
      "Received as 'more or less one of us' — and nurturing the next grower in",
    ],
  },
];

export const phaseById = (id: number) => PHASES.find((p) => p.id === id) ?? PHASES[0];
export const phaseBySlug = (slug: string) => PHASES.find((p) => p.slug === slug);

export const TOTAL_HOURS = 1500;

/** Where a grower stands inside their current phase, 0..100 */
export function phaseProgress(phase: Phase, hoursLogged: number): number {
  const into = hoursLogged - phase.startHour;
  return Math.min(100, Math.max(0, (into / phase.hours) * 100));
}
