import type { VocabDomain } from "./types";

/**
 * Digital picture-card decks — the heart of GPA Phase 1–2 practice.
 * Like the nurturer's photo cards: meaning is carried by the IMAGE,
 * never by translation into the grower's language.
 */
export const VOCAB_DOMAINS: VocabDomain[] = [
  {
    id: "food",
    emoji: "🍎",
    color: "violet",
    names: { en: "Food", es: "Comida", ru: "Еда", fr: "Nourriture", de: "Essen", pt: "Comida", it: "Cibo" },
    items: [
      { id: "apple", emoji: "🍎", words: { es: "la manzana", ru: "яблоко", fr: "la pomme", de: "der Apfel", pt: "a maçã", it: "la mela" } },
      { id: "bread", emoji: "🍞", words: { es: "el pan", ru: "хлеб", fr: "le pain", de: "das Brot", pt: "o pão", it: "il pane" } },
      { id: "milk", emoji: "🥛", words: { es: "la leche", ru: "молоко", fr: "le lait", de: "die Milch", pt: "o leite", it: "il latte" } },
      { id: "egg", emoji: "🥚", words: { es: "el huevo", ru: "яйцо", fr: "l'œuf", de: "das Ei", pt: "o ovo", it: "l'uovo" } },
      { id: "fish", emoji: "🐟", words: { es: "el pescado", ru: "рыба", fr: "le poisson", de: "der Fisch", pt: "o peixe", it: "il pesce" } },
      { id: "cheese", emoji: "🧀", words: { es: "el queso", ru: "сыр", fr: "le fromage", de: "der Käse", pt: "o queijo", it: "il formaggio" } },
      { id: "water", emoji: "💧", words: { es: "el agua", ru: "вода", fr: "l'eau", de: "das Wasser", pt: "a água", it: "l'acqua" } },
      { id: "coffee", emoji: "☕", words: { es: "el café", ru: "кофе", fr: "le café", de: "der Kaffee", pt: "o café", it: "il caffè" } },
      { id: "rice", emoji: "🍚", words: { es: "el arroz", ru: "рис", fr: "le riz", de: "der Reis", pt: "o arroz", it: "il riso" } },
      { id: "soup", emoji: "🍲", words: { es: "la sopa", ru: "суп", fr: "la soupe", de: "die Suppe", pt: "a sopa", it: "la zuppa" } },
      { id: "banana", emoji: "🍌", words: { es: "el plátano", ru: "банан", fr: "la banane", de: "die Banane", pt: "a banana", it: "la banana" } },
      { id: "tomato", emoji: "🍅", words: { es: "el tomate", ru: "помидор", fr: "la tomate", de: "die Tomate", pt: "o tomate", it: "il pomodoro" } },
    ],
  },
  {
    id: "animals",
    emoji: "🐾",
    color: "lime",
    names: { en: "Animals", es: "Animales", ru: "Животные", fr: "Animaux", de: "Tiere", pt: "Animais", it: "Animali" },
    items: [
      { id: "dog", emoji: "🐕", words: { es: "el perro", ru: "собака", fr: "le chien", de: "der Hund", pt: "o cachorro", it: "il cane" } },
      { id: "cat", emoji: "🐈", words: { es: "el gato", ru: "кошка", fr: "le chat", de: "die Katze", pt: "o gato", it: "il gatto" } },
      { id: "bird", emoji: "🐦", words: { es: "el pájaro", ru: "птица", fr: "l'oiseau", de: "der Vogel", pt: "o pássaro", it: "l'uccello" } },
      { id: "horse", emoji: "🐎", words: { es: "el caballo", ru: "лошадь", fr: "le cheval", de: "das Pferd", pt: "o cavalo", it: "il cavallo" } },
      { id: "cow", emoji: "🐄", words: { es: "la vaca", ru: "корова", fr: "la vache", de: "die Kuh", pt: "a vaca", it: "la mucca" } },
      { id: "sheep", emoji: "🐑", words: { es: "la oveja", ru: "овца", fr: "le mouton", de: "das Schaf", pt: "a ovelha", it: "la pecora" } },
      { id: "chicken", emoji: "🐔", words: { es: "la gallina", ru: "курица", fr: "la poule", de: "das Huhn", pt: "a galinha", it: "la gallina" } },
      { id: "bear", emoji: "🐻", words: { es: "el oso", ru: "медведь", fr: "l'ours", de: "der Bär", pt: "o urso", it: "l'orso" } },
      { id: "rabbit", emoji: "🐇", words: { es: "el conejo", ru: "кролик", fr: "le lapin", de: "der Hase", pt: "o coelho", it: "il coniglio" } },
      { id: "mouse", emoji: "🐭", words: { es: "el ratón", ru: "мышь", fr: "la souris", de: "die Maus", pt: "o rato", it: "il topo" } },
      { id: "frog", emoji: "🐸", words: { es: "la rana", ru: "лягушка", fr: "la grenouille", de: "der Frosch", pt: "o sapo", it: "la rana" } },
      { id: "butterfly", emoji: "🦋", words: { es: "la mariposa", ru: "бабочка", fr: "le papillon", de: "der Schmetterling", pt: "a borboleta", it: "la farfalla" } },
    ],
  },
  {
    id: "home",
    emoji: "🏠",
    color: "orange",
    names: { en: "Home", es: "Casa", ru: "Дом", fr: "Maison", de: "Zuhause", pt: "Casa", it: "Casa" },
    items: [
      { id: "house", emoji: "🏠", words: { es: "la casa", ru: "дом", fr: "la maison", de: "das Haus", pt: "a casa", it: "la casa" } },
      { id: "door", emoji: "🚪", words: { es: "la puerta", ru: "дверь", fr: "la porte", de: "die Tür", pt: "a porta", it: "la porta" } },
      { id: "window", emoji: "🪟", words: { es: "la ventana", ru: "окно", fr: "la fenêtre", de: "das Fenster", pt: "a janela", it: "la finestra" } },
      { id: "bed", emoji: "🛏️", words: { es: "la cama", ru: "кровать", fr: "le lit", de: "das Bett", pt: "a cama", it: "il letto" } },
      { id: "chair", emoji: "🪑", words: { es: "la silla", ru: "стул", fr: "la chaise", de: "der Stuhl", pt: "a cadeira", it: "la sedia" } },
      { id: "key", emoji: "🔑", words: { es: "la llave", ru: "ключ", fr: "la clé", de: "der Schlüssel", pt: "a chave", it: "la chiave" } },
      { id: "lamp", emoji: "💡", words: { es: "la lámpara", ru: "лампа", fr: "la lampe", de: "die Lampe", pt: "a lâmpada", it: "la lampada" } },
      { id: "clock", emoji: "🕐", words: { es: "el reloj", ru: "часы", fr: "l'horloge", de: "die Uhr", pt: "o relógio", it: "l'orologio" } },
      { id: "book", emoji: "📖", words: { es: "el libro", ru: "книга", fr: "le livre", de: "das Buch", pt: "o livro", it: "il libro" } },
      { id: "phone", emoji: "📱", words: { es: "el teléfono", ru: "телефон", fr: "le téléphone", de: "das Telefon", pt: "o telefone", it: "il telefono" } },
      { id: "cup", emoji: "🍵", words: { es: "la taza", ru: "чашка", fr: "la tasse", de: "die Tasse", pt: "a xícara", it: "la tazza" } },
      { id: "table", emoji: "🪵", words: { es: "la mesa", ru: "стол", fr: "la table", de: "der Tisch", pt: "a mesa", it: "il tavolo" } },
    ],
  },
  {
    id: "body",
    emoji: "👋",
    color: "lemon",
    names: { en: "Body", es: "Cuerpo", ru: "Тело", fr: "Corps", de: "Körper", pt: "Corpo", it: "Corpo" },
    items: [
      { id: "hand", emoji: "✋", words: { es: "la mano", ru: "рука", fr: "la main", de: "die Hand", pt: "a mão", it: "la mano" } },
      { id: "eye", emoji: "👁️", words: { es: "el ojo", ru: "глаз", fr: "l'œil", de: "das Auge", pt: "o olho", it: "l'occhio" } },
      { id: "ear", emoji: "👂", words: { es: "la oreja", ru: "ухо", fr: "l'oreille", de: "das Ohr", pt: "a orelha", it: "l'orecchio" } },
      { id: "nose", emoji: "👃", words: { es: "la nariz", ru: "нос", fr: "le nez", de: "die Nase", pt: "o nariz", it: "il naso" } },
      { id: "mouth", emoji: "👄", words: { es: "la boca", ru: "рот", fr: "la bouche", de: "der Mund", pt: "a boca", it: "la bocca" } },
      { id: "foot", emoji: "🦶", words: { es: "el pie", ru: "нога", fr: "le pied", de: "der Fuß", pt: "o pé", it: "il piede" } },
      { id: "head", emoji: "🙂", words: { es: "la cabeza", ru: "голова", fr: "la tête", de: "der Kopf", pt: "a cabeça", it: "la testa" } },
      { id: "tooth", emoji: "🦷", words: { es: "el diente", ru: "зуб", fr: "la dent", de: "der Zahn", pt: "o dente", it: "il dente" } },
      { id: "hair", emoji: "💇", words: { es: "el pelo", ru: "волосы", fr: "les cheveux", de: "die Haare", pt: "o cabelo", it: "i capelli" } },
      { id: "heart", emoji: "❤️", words: { es: "el corazón", ru: "сердце", fr: "le cœur", de: "das Herz", pt: "o coração", it: "il cuore" } },
    ],
  },
  {
    id: "traveling",
    emoji: "✈️",
    color: "orange",
    names: { en: "Traveling", es: "Viajes", ru: "Путешествия", fr: "Voyages", de: "Reisen", pt: "Viagens", it: "Viaggi" },
    items: [
      { id: "car", emoji: "🚗", words: { es: "el coche", ru: "машина", fr: "la voiture", de: "das Auto", pt: "o carro", it: "la macchina" } },
      { id: "bus", emoji: "🚌", words: { es: "el autobús", ru: "автобус", fr: "le bus", de: "der Bus", pt: "o ônibus", it: "l'autobus" } },
      { id: "train", emoji: "🚆", words: { es: "el tren", ru: "поезд", fr: "le train", de: "der Zug", pt: "o trem", it: "il treno" } },
      { id: "plane", emoji: "✈️", words: { es: "el avión", ru: "самолёт", fr: "l'avion", de: "das Flugzeug", pt: "o avião", it: "l'aereo" } },
      { id: "bicycle", emoji: "🚲", words: { es: "la bicicleta", ru: "велосипед", fr: "le vélo", de: "das Fahrrad", pt: "a bicicleta", it: "la bicicletta" } },
      { id: "boat", emoji: "⛵", words: { es: "el barco", ru: "лодка", fr: "le bateau", de: "das Boot", pt: "o barco", it: "la barca" } },
      { id: "map", emoji: "🗺️", words: { es: "el mapa", ru: "карта", fr: "la carte", de: "die Karte", pt: "o mapa", it: "la mappa" } },
      { id: "suitcase", emoji: "🧳", words: { es: "la maleta", ru: "чемодан", fr: "la valise", de: "der Koffer", pt: "a mala", it: "la valigia" } },
      { id: "ticket", emoji: "🎫", words: { es: "el billete", ru: "билет", fr: "le billet", de: "die Fahrkarte", pt: "o bilhete", it: "il biglietto" } },
      { id: "road", emoji: "🛣️", words: { es: "la carretera", ru: "дорога", fr: "la route", de: "die Straße", pt: "a estrada", it: "la strada" } },
    ],
  },
  {
    id: "family",
    emoji: "👨‍👩‍👧",
    color: "violet",
    names: { en: "Family", es: "Familia", ru: "Семья", fr: "Famille", de: "Familie", pt: "Família", it: "Famiglia" },
    items: [
      { id: "mother", emoji: "👩", words: { es: "la madre", ru: "мама", fr: "la mère", de: "die Mutter", pt: "a mãe", it: "la madre" } },
      { id: "father", emoji: "👨", words: { es: "el padre", ru: "папа", fr: "le père", de: "der Vater", pt: "o pai", it: "il padre" } },
      { id: "baby", emoji: "👶", words: { es: "el bebé", ru: "малыш", fr: "le bébé", de: "das Baby", pt: "o bebê", it: "il bambino" } },
      { id: "grandma", emoji: "👵", words: { es: "la abuela", ru: "бабушка", fr: "la grand-mère", de: "die Oma", pt: "a avó", it: "la nonna" } },
      { id: "grandpa", emoji: "👴", words: { es: "el abuelo", ru: "дедушка", fr: "le grand-père", de: "der Opa", pt: "o avô", it: "il nonno" } },
      { id: "boy", emoji: "👦", words: { es: "el niño", ru: "мальчик", fr: "le garçon", de: "der Junge", pt: "o menino", it: "il ragazzo" } },
      { id: "girl", emoji: "👧", words: { es: "la niña", ru: "девочка", fr: "la fille", de: "das Mädchen", pt: "a menina", it: "la ragazza" } },
      { id: "friends", emoji: "🧑‍🤝‍🧑", words: { es: "los amigos", ru: "друзья", fr: "les amis", de: "die Freunde", pt: "os amigos", it: "gli amici" } },
    ],
  },
  {
    id: "sport",
    emoji: "⚽",
    color: "lime",
    names: { en: "Sport", es: "Deporte", ru: "Спорт", fr: "Sport", de: "Sport", pt: "Esporte", it: "Sport" },
    items: [
      { id: "ball", emoji: "⚽", words: { es: "el balón", ru: "мяч", fr: "le ballon", de: "der Ball", pt: "a bola", it: "il pallone" } },
      { id: "run", emoji: "🏃", words: { es: "correr", ru: "бегать", fr: "courir", de: "laufen", pt: "correr", it: "correre" } },
      { id: "swim", emoji: "🏊", words: { es: "nadar", ru: "плавать", fr: "nager", de: "schwimmen", pt: "nadar", it: "nuotare" } },
      { id: "jump", emoji: "🤸", words: { es: "saltar", ru: "прыгать", fr: "sauter", de: "springen", pt: "pular", it: "saltare" } },
      { id: "dance", emoji: "💃", words: { es: "bailar", ru: "танцевать", fr: "danser", de: "tanzen", pt: "dançar", it: "ballare" } },
      { id: "basketball", emoji: "🏀", words: { es: "el baloncesto", ru: "баскетбол", fr: "le basket", de: "der Basketball", pt: "o basquete", it: "il basket" } },
      { id: "tennis", emoji: "🎾", words: { es: "el tenis", ru: "теннис", fr: "le tennis", de: "das Tennis", pt: "o tênis", it: "il tennis" } },
      { id: "ski", emoji: "⛷️", words: { es: "esquiar", ru: "кататься на лыжах", fr: "skier", de: "Ski fahren", pt: "esquiar", it: "sciare" } },
    ],
  },
  {
    id: "health",
    emoji: "🩺",
    color: "coral",
    names: { en: "Health", es: "Salud", ru: "Здоровье", fr: "Santé", de: "Gesundheit", pt: "Saúde", it: "Salute" },
    items: [
      { id: "doctor", emoji: "🧑‍⚕️", words: { es: "el médico", ru: "врач", fr: "le médecin", de: "der Arzt", pt: "o médico", it: "il medico" } },
      { id: "medicine", emoji: "💊", words: { es: "la medicina", ru: "лекарство", fr: "le médicament", de: "die Medizin", pt: "o remédio", it: "la medicina" } },
      { id: "hospital", emoji: "🏥", words: { es: "el hospital", ru: "больница", fr: "l'hôpital", de: "das Krankenhaus", pt: "o hospital", it: "l'ospedale" } },
      { id: "sleep", emoji: "😴", words: { es: "dormir", ru: "спать", fr: "dormir", de: "schlafen", pt: "dormir", it: "dormire" } },
      { id: "eat", emoji: "🍽️", words: { es: "comer", ru: "есть", fr: "manger", de: "essen", pt: "comer", it: "mangiare" } },
      { id: "drink", emoji: "🥤", words: { es: "beber", ru: "пить", fr: "boire", de: "trinken", pt: "beber", it: "bere" } },
      { id: "wash", emoji: "🧼", words: { es: "lavar", ru: "мыть", fr: "laver", de: "waschen", pt: "lavar", it: "lavare" } },
      { id: "tooth-brush", emoji: "🪥", words: { es: "el cepillo", ru: "зубная щётка", fr: "la brosse à dents", de: "die Zahnbürste", pt: "a escova", it: "lo spazzolino" } },
    ],
  },
  {
    id: "nature",
    emoji: "🌳",
    color: "mint",
    names: { en: "Nature", es: "Naturaleza", ru: "Природа", fr: "Nature", de: "Natur", pt: "Natureza", it: "Natura" },
    items: [
      { id: "sun", emoji: "☀️", words: { es: "el sol", ru: "солнце", fr: "le soleil", de: "die Sonne", pt: "o sol", it: "il sole" } },
      { id: "moon", emoji: "🌙", words: { es: "la luna", ru: "луна", fr: "la lune", de: "der Mond", pt: "a lua", it: "la luna" } },
      { id: "tree", emoji: "🌳", words: { es: "el árbol", ru: "дерево", fr: "l'arbre", de: "der Baum", pt: "a árvore", it: "l'albero" } },
      { id: "flower", emoji: "🌸", words: { es: "la flor", ru: "цветок", fr: "la fleur", de: "die Blume", pt: "a flor", it: "il fiore" } },
      { id: "rain", emoji: "🌧️", words: { es: "la lluvia", ru: "дождь", fr: "la pluie", de: "der Regen", pt: "a chuva", it: "la pioggia" } },
      { id: "snow", emoji: "❄️", words: { es: "la nieve", ru: "снег", fr: "la neige", de: "der Schnee", pt: "a neve", it: "la neve" } },
      { id: "mountain", emoji: "⛰️", words: { es: "la montaña", ru: "гора", fr: "la montagne", de: "der Berg", pt: "a montanha", it: "la montagna" } },
      { id: "sea", emoji: "🌊", words: { es: "el mar", ru: "море", fr: "la mer", de: "das Meer", pt: "o mar", it: "il mare" } },
      { id: "fire", emoji: "🔥", words: { es: "el fuego", ru: "огонь", fr: "le feu", de: "das Feuer", pt: "o fogo", it: "il fuoco" } },
      { id: "star", emoji: "⭐", words: { es: "la estrella", ru: "звезда", fr: "l'étoile", de: "der Stern", pt: "a estrela", it: "la stella" } },
    ],
  },
  {
    id: "work",
    emoji: "💼",
    color: "violet",
    names: { en: "Work", es: "Trabajo", ru: "Работа", fr: "Travail", de: "Arbeit", pt: "Trabalho", it: "Lavoro" },
    items: [
      { id: "computer", emoji: "💻", words: { es: "el ordenador", ru: "компьютер", fr: "l'ordinateur", de: "der Computer", pt: "o computador", it: "il computer" } },
      { id: "pen", emoji: "🖊️", words: { es: "el bolígrafo", ru: "ручка", fr: "le stylo", de: "der Stift", pt: "a caneta", it: "la penna" } },
      { id: "paper", emoji: "📄", words: { es: "el papel", ru: "бумага", fr: "le papier", de: "das Papier", pt: "o papel", it: "la carta" } },
      { id: "money", emoji: "💰", words: { es: "el dinero", ru: "деньги", fr: "l'argent", de: "das Geld", pt: "o dinheiro", it: "i soldi" } },
      { id: "teacher", emoji: "🧑‍🏫", words: { es: "el profesor", ru: "учитель", fr: "le professeur", de: "der Lehrer", pt: "o professor", it: "l'insegnante" } },
      { id: "farmer", emoji: "🧑‍🌾", words: { es: "el agricultor", ru: "фермер", fr: "le fermier", de: "der Bauer", pt: "o agricultor", it: "il contadino" } },
      { id: "cook", emoji: "🧑‍🍳", words: { es: "el cocinero", ru: "повар", fr: "le cuisinier", de: "der Koch", pt: "o cozinheiro", it: "il cuoco" } },
      { id: "shop", emoji: "🏪", words: { es: "la tienda", ru: "магазин", fr: "le magasin", de: "der Laden", pt: "a loja", it: "il negozio" } },
    ],
  },
];

export const domainById = (id: string) => VOCAB_DOMAINS.find((d) => d.id === id);

/** TPR-style action commands for the listening trainer (Phase 1 "Total Physical Response") */
export const TPR_COMMANDS: { id: string; emoji: string; words: Partial<Record<string, string>> }[] = [
  { id: "stand", emoji: "🧍", words: { es: "¡Levántate!", ru: "Встань!", fr: "Lève-toi !", de: "Steh auf!", pt: "Levanta-te!", it: "Alzati!" } },
  { id: "sit", emoji: "🪑", words: { es: "¡Siéntate!", ru: "Сядь!", fr: "Assieds-toi !", de: "Setz dich!", pt: "Senta-te!", it: "Siediti!" } },
  { id: "point", emoji: "👉", words: { es: "¡Señala!", ru: "Покажи!", fr: "Montre !", de: "Zeig!", pt: "Aponta!", it: "Indica!" } },
  { id: "take", emoji: "🤲", words: { es: "¡Toma!", ru: "Возьми!", fr: "Prends !", de: "Nimm!", pt: "Pega!", it: "Prendi!" } },
  { id: "give", emoji: "🫴", words: { es: "¡Dame!", ru: "Дай!", fr: "Donne !", de: "Gib!", pt: "Dá!", it: "Dammi!" } },
  { id: "open", emoji: "📂", words: { es: "¡Abre!", ru: "Открой!", fr: "Ouvre !", de: "Öffne!", pt: "Abre!", it: "Apri!" } },
  { id: "close", emoji: "📁", words: { es: "¡Cierra!", ru: "Закрой!", fr: "Ferme !", de: "Schließ!", pt: "Fecha!", it: "Chiudi!" } },
  { id: "walk", emoji: "🚶", words: { es: "¡Camina!", ru: "Иди!", fr: "Marche !", de: "Geh!", pt: "Anda!", it: "Cammina!" } },
];
