import type { VocabDomain } from "./types";

/**
 * Digital picture-card decks — the heart of GPA Phase 1–2 practice.
 * Like the nurturer's photo cards: meaning is carried by the IMAGE,
 * never by translation into the grower's language.
 */
export const VOCAB_DOMAINS: VocabDomain[] = [
  {
    id: "food",
    emoji: "🍎",
    color: "violet",
    names: { en: "Food", es: "Comida", ru: "Еда", fr: "Nourriture", de: "Essen", pt: "Comida", it: "Cibo", ja: "食べ物", zh: "食物" },
    items: [
      { id: "apple", emoji: "🍎", words: { en: "apple", es: "la manzana", ru: "яблоко", fr: "la pomme", de: "der Apfel", pt: "a maçã", it: "la mela", ja: "りんご", zh: "苹果", ht: "pòm" } },
      { id: "bread", emoji: "🍞", words: { en: "bread", es: "el pan", ru: "хлеб", fr: "le pain", de: "das Brot", pt: "o pão", it: "il pane", ja: "パン", zh: "面包", ht: "pen" } },
      { id: "milk", emoji: "🥛", words: { en: "milk", es: "la leche", ru: "молоко", fr: "le lait", de: "die Milch", pt: "o leite", it: "il latte", ja: "牛乳", zh: "牛奶", ht: "lèt" } },
      { id: "egg", emoji: "🥚", words: { en: "egg", es: "el huevo", ru: "яйцо", fr: "l'œuf", de: "das Ei", pt: "o ovo", it: "l'uovo", ja: "卵", zh: "鸡蛋", ht: "ze" } },
      { id: "fish", emoji: "🐟", words: { en: "fish", es: "el pescado", ru: "рыба", fr: "le poisson", de: "der Fisch", pt: "o peixe", it: "il pesce", ja: "魚", zh: "鱼", ht: "pwason" } },
      { id: "cheese", emoji: "🧀", words: { en: "cheese", es: "el queso", ru: "сыр", fr: "le fromage", de: "der Käse", pt: "o queijo", it: "il formaggio", ja: "チーズ", zh: "奶酪", ht: "fwomaj" } },
      { id: "water", emoji: "💧", words: { en: "water", es: "el agua", ru: "вода", fr: "l'eau", de: "das Wasser", pt: "a água", it: "l'acqua", ja: "水", zh: "水", ht: "dlo" } },
      { id: "coffee", emoji: "☕", words: { en: "coffee", es: "el café", ru: "кофе", fr: "le café", de: "der Kaffee", pt: "o café", it: "il caffè", ja: "コーヒー", zh: "咖啡", ht: "kafe" } },
      { id: "rice", emoji: "🍚", words: { en: "rice", es: "el arroz", ru: "рис", fr: "le riz", de: "der Reis", pt: "o arroz", it: "il riso", ja: "ご飯", zh: "米饭", ht: "diri" } },
      { id: "soup", emoji: "🍲", words: { en: "soup", es: "la sopa", ru: "суп", fr: "la soupe", de: "die Suppe", pt: "a sopa", it: "la zuppa", ja: "スープ", zh: "汤", ht: "soup" } },
      { id: "banana", emoji: "🍌", words: { en: "banana", es: "el plátano", ru: "банан", fr: "la banane", de: "die Banane", pt: "a banana", it: "la banana", ja: "バナナ", zh: "香蕉", ht: "fig" } },
      { id: "tomato", emoji: "🍅", words: { en: "tomato", es: "el tomate", ru: "помидор", fr: "la tomate", de: "die Tomate", pt: "o tomate", it: "il pomodoro", ja: "トマト", zh: "西红柿", ht: "tomat" } },
    ],
  },
  {
    id: "animals",
    emoji: "🐾",
    color: "lime",
    names: { en: "Animals", es: "Animales", ru: "Животные", fr: "Animaux", de: "Tiere", pt: "Animais", it: "Animali", ja: "動物", zh: "动物" },
    items: [
      { id: "dog", emoji: "🐕", words: { en: "dog", es: "el perro", ru: "собака", fr: "le chien", de: "der Hund", pt: "o cachorro", it: "il cane", ja: "犬", zh: "狗", ht: "chen" } },
      { id: "cat", emoji: "🐈", words: { en: "cat", es: "el gato", ru: "кошка", fr: "le chat", de: "die Katze", pt: "o gato", it: "il gatto", ja: "猫", zh: "猫", ht: "chat" } },
      { id: "bird", emoji: "🐦", words: { en: "bird", es: "el pájaro", ru: "птица", fr: "l'oiseau", de: "der Vogel", pt: "o pássaro", it: "l'uccello", ja: "鳥", zh: "鸟", ht: "zwazo" } },
      { id: "horse", emoji: "🐎", words: { en: "horse", es: "el caballo", ru: "лошадь", fr: "le cheval", de: "das Pferd", pt: "o cavalo", it: "il cavallo", ja: "馬", zh: "马", ht: "chwal" } },
      { id: "cow", emoji: "🐄", words: { en: "cow", es: "la vaca", ru: "корова", fr: "la vache", de: "die Kuh", pt: "a vaca", it: "la mucca", ja: "牛", zh: "奶牛", ht: "bèf" } },
      { id: "sheep", emoji: "🐑", words: { en: "sheep", es: "la oveja", ru: "овца", fr: "le mouton", de: "das Schaf", pt: "a ovelha", it: "la pecora", ja: "羊", zh: "羊", ht: "mouton" } },
      { id: "chicken", emoji: "🐔", words: { en: "chicken", es: "la gallina", ru: "курица", fr: "la poule", de: "das Huhn", pt: "a galinha", it: "la gallina", ja: "にわとり", zh: "鸡", ht: "poul" } },
      { id: "bear", emoji: "🐻", words: { en: "bear", es: "el oso", ru: "медведь", fr: "l'ours", de: "der Bär", pt: "o urso", it: "l'orso", ja: "熊", zh: "熊", ht: "lous" } },
      { id: "rabbit", emoji: "🐇", words: { en: "rabbit", es: "el conejo", ru: "кролик", fr: "le lapin", de: "der Hase", pt: "o coelho", it: "il coniglio", ja: "うさぎ", zh: "兔子", ht: "lapen" } },
      { id: "mouse", emoji: "🐭", words: { en: "mouse", es: "el ratón", ru: "мышь", fr: "la souris", de: "die Maus", pt: "o rato", it: "il topo", ja: "ねずみ", zh: "老鼠", ht: "sourit" } },
      { id: "frog", emoji: "🐸", words: { en: "frog", es: "la rana", ru: "лягушка", fr: "la grenouille", de: "der Frosch", pt: "o sapo", it: "la rana", ja: "カエル", zh: "青蛙", ht: "krapo" } },
      { id: "butterfly", emoji: "🦋", words: { en: "butterfly", es: "la mariposa", ru: "бабочка", fr: "le papillon", de: "der Schmetterling", pt: "a borboleta", it: "la farfalla", ja: "ちょうちょ", zh: "蝴蝶", ht: "papiyon" } },
    ],
  },
  {
    id: "home",
    emoji: "🏠",
    color: "orange",
    names: { en: "Home", es: "Casa", ru: "Дом", fr: "Maison", de: "Zuhause", pt: "Casa", it: "Casa", ja: "家", zh: "家" },
    items: [
      { id: "house", emoji: "🏠", words: { en: "house", es: "la casa", ru: "дом", fr: "la maison", de: "das Haus", pt: "a casa", it: "la casa", ja: "家", zh: "房子", ht: "kay" } },
      { id: "door", emoji: "🚪", words: { en: "door", es: "la puerta", ru: "дверь", fr: "la porte", de: "die Tür", pt: "a porta", it: "la porta", ja: "ドア", zh: "门", ht: "pòt" } },
      { id: "window", emoji: "🪟", words: { en: "window", es: "la ventana", ru: "окно", fr: "la fenêtre", de: "das Fenster", pt: "a janela", it: "la finestra", ja: "窓", zh: "窗户", ht: "fenèt" } },
      { id: "bed", emoji: "🛏️", words: { en: "bed", es: "la cama", ru: "кровать", fr: "le lit", de: "das Bett", pt: "a cama", it: "il letto", ja: "ベッド", zh: "床", ht: "kabann" } },
      { id: "chair", emoji: "🪑", words: { en: "chair", es: "la silla", ru: "стул", fr: "la chaise", de: "der Stuhl", pt: "a cadeira", it: "la sedia", ja: "椅子", zh: "椅子", ht: "chèz" } },
      { id: "key", emoji: "🔑", words: { en: "key", es: "la llave", ru: "ключ", fr: "la clé", de: "der Schlüssel", pt: "a chave", it: "la chiave", ja: "鍵", zh: "钥匙", ht: "kle" } },
      { id: "lamp", emoji: "💡", words: { en: "lamp", es: "la lámpara", ru: "лампа", fr: "la lampe", de: "die Lampe", pt: "a lâmpada", it: "la lampada", ja: "ランプ", zh: "灯", ht: "lanp" } },
      { id: "clock", emoji: "🕐", words: { en: "clock", es: "el reloj", ru: "часы", fr: "l'horloge", de: "die Uhr", pt: "o relógio", it: "l'orologio", ja: "時計", zh: "钟", ht: "revèy" } },
      { id: "book", emoji: "📖", words: { en: "book", es: "el libro", ru: "книга", fr: "le livre", de: "das Buch", pt: "o livro", it: "il libro", ja: "本", zh: "书", ht: "liv" } },
      { id: "phone", emoji: "📱", words: { en: "phone", es: "el teléfono", ru: "телефон", fr: "le téléphone", de: "das Telefon", pt: "o telefone", it: "il telefono", ja: "電話", zh: "手机", ht: "telefòn" } },
      { id: "cup", emoji: "🍵", words: { en: "cup", es: "la taza", ru: "чашка", fr: "la tasse", de: "die Tasse", pt: "a xícara", it: "la tazza", ja: "コップ", zh: "杯子", ht: "tas" } },
      { id: "table", emoji: "🪵", words: { en: "table", es: "la mesa", ru: "стол", fr: "la table", de: "der Tisch", pt: "a mesa", it: "il tavolo", ja: "テーブル", zh: "桌子", ht: "tab" } },
    ],
  },
  {
    id: "body",
    emoji: "👋",
    color: "lemon",
    names: { en: "Body", es: "Cuerpo", ru: "Тело", fr: "Corps", de: "Körper", pt: "Corpo", it: "Corpo", ja: "体", zh: "身体" },
    items: [
      { id: "hand", emoji: "✋", words: { en: "hand", es: "la mano", ru: "рука", fr: "la main", de: "die Hand", pt: "a mão", it: "la mano", ja: "手", zh: "手", ht: "men" } },
      { id: "eye", emoji: "👁️", words: { en: "eye", es: "el ojo", ru: "глаз", fr: "l'œil", de: "das Auge", pt: "o olho", it: "l'occhio", ja: "目", zh: "眼睛", ht: "je" } },
      { id: "ear", emoji: "👂", words: { en: "ear", es: "la oreja", ru: "ухо", fr: "l'oreille", de: "das Ohr", pt: "a orelha", it: "l'orecchio", ja: "耳", zh: "耳朵", ht: "zòrèy" } },
      { id: "nose", emoji: "👃", words: { en: "nose", es: "la nariz", ru: "нос", fr: "le nez", de: "die Nase", pt: "o nariz", it: "il naso", ja: "鼻", zh: "鼻子", ht: "nen" } },
      { id: "mouth", emoji: "👄", words: { en: "mouth", es: "la boca", ru: "рот", fr: "la bouche", de: "der Mund", pt: "a boca", it: "la bocca", ja: "口", zh: "嘴巴", ht: "bouch" } },
      { id: "foot", emoji: "🦶", words: { en: "foot", es: "el pie", ru: "нога", fr: "le pied", de: "der Fuß", pt: "o pé", it: "il piede", ja: "足", zh: "脚", ht: "pye" } },
      { id: "head", emoji: "🙂", words: { en: "head", es: "la cabeza", ru: "голова", fr: "la tête", de: "der Kopf", pt: "a cabeça", it: "la testa", ja: "頭", zh: "头", ht: "tèt" } },
      { id: "tooth", emoji: "🦷", words: { en: "tooth", es: "el diente", ru: "зуб", fr: "la dent", de: "der Zahn", pt: "o dente", it: "il dente", ja: "歯", zh: "牙齿", ht: "dan" } },
      { id: "hair", emoji: "💇", words: { en: "hair", es: "el pelo", ru: "волосы", fr: "les cheveux", de: "die Haare", pt: "o cabelo", it: "i capelli", ja: "髪", zh: "头发", ht: "cheve" } },
      { id: "heart", emoji: "❤️", words: { en: "heart", es: "el corazón", ru: "сердце", fr: "le cœur", de: "das Herz", pt: "o coração", it: "il cuore", ja: "心臓", zh: "心脏", ht: "kè" } },
    ],
  },
  {
    id: "traveling",
    emoji: "✈️",
    color: "orange",
    names: { en: "Traveling", es: "Viajes", ru: "Путешествия", fr: "Voyages", de: "Reisen", pt: "Viagens", it: "Viaggi", ja: "旅行", zh: "旅行" },
    items: [
      { id: "car", emoji: "🚗", words: { en: "car", es: "el coche", ru: "машина", fr: "la voiture", de: "das Auto", pt: "o carro", it: "la macchina", ja: "車", zh: "汽车", ht: "machin" } },
      { id: "bus", emoji: "🚌", words: { en: "bus", es: "el autobús", ru: "автобус", fr: "le bus", de: "der Bus", pt: "o ônibus", it: "l'autobus", ja: "バス", zh: "公交车", ht: "bis" } },
      { id: "train", emoji: "🚆", words: { en: "train", es: "el tren", ru: "поезд", fr: "le train", de: "der Zug", pt: "o trem", it: "il treno", ja: "電車", zh: "火车", ht: "tren" } },
      { id: "plane", emoji: "✈️", words: { en: "plane", es: "el avión", ru: "самолёт", fr: "l'avion", de: "das Flugzeug", pt: "o avião", it: "l'aereo", ja: "飛行機", zh: "飞机", ht: "avyon" } },
      { id: "bicycle", emoji: "🚲", words: { en: "bicycle", es: "la bicicleta", ru: "велосипед", fr: "le vélo", de: "das Fahrrad", pt: "a bicicleta", it: "la bicicletta", ja: "自転車", zh: "自行车", ht: "bisiklèt" } },
      { id: "boat", emoji: "⛵", words: { en: "boat", es: "el barco", ru: "лодка", fr: "le bateau", de: "das Boot", pt: "o barco", it: "la barca", ja: "船", zh: "船", ht: "bato" } },
      { id: "map", emoji: "🗺️", words: { en: "map", es: "el mapa", ru: "карта", fr: "la carte", de: "die Karte", pt: "o mapa", it: "la mappa", ja: "地図", zh: "地图", ht: "kat" } },
      { id: "suitcase", emoji: "🧳", words: { en: "suitcase", es: "la maleta", ru: "чемодан", fr: "la valise", de: "der Koffer", pt: "a mala", it: "la valigia", ja: "スーツケース", zh: "行李箱", ht: "valiz" } },
      { id: "ticket", emoji: "🎫", words: { en: "ticket", es: "el billete", ru: "билет", fr: "le billet", de: "die Fahrkarte", pt: "o bilhete", it: "il biglietto", ja: "切符", zh: "票", ht: "tikè" } },
      { id: "road", emoji: "🛣️", words: { en: "road", es: "la carretera", ru: "дорога", fr: "la route", de: "die Straße", pt: "a estrada", it: "la strada", ja: "道", zh: "路", ht: "wout" } },
    ],
  },
  {
    id: "family",
    emoji: "👨‍👩‍👧",
    color: "violet",
    names: { en: "Family", es: "Familia", ru: "Семья", fr: "Famille", de: "Familie", pt: "Família", it: "Famiglia", ja: "家族", zh: "家庭" },
    items: [
      { id: "mother", emoji: "👩", words: { en: "mother", es: "la madre", ru: "мама", fr: "la mère", de: "die Mutter", pt: "a mãe", it: "la madre", ja: "お母さん", zh: "妈妈", ht: "manman" } },
      { id: "father", emoji: "👨", words: { en: "father", es: "el padre", ru: "папа", fr: "le père", de: "der Vater", pt: "o pai", it: "il padre", ja: "お父さん", zh: "爸爸", ht: "papa" } },
      { id: "baby", emoji: "👶", words: { en: "baby", es: "el bebé", ru: "малыш", fr: "le bébé", de: "das Baby", pt: "o bebê", it: "il bambino", ja: "赤ちゃん", zh: "宝宝", ht: "tibebe" } },
      { id: "grandma", emoji: "👵", words: { en: "grandma", es: "la abuela", ru: "бабушка", fr: "la grand-mère", de: "die Oma", pt: "a avó", it: "la nonna", ja: "おばあちゃん", zh: "奶奶", ht: "grann" } },
      { id: "grandpa", emoji: "👴", words: { en: "grandpa", es: "el abuelo", ru: "дедушка", fr: "le grand-père", de: "der Opa", pt: "o avô", it: "il nonno", ja: "おじいちゃん", zh: "爷爷", ht: "granpapa" } },
      { id: "boy", emoji: "👦", words: { en: "boy", es: "el niño", ru: "мальчик", fr: "le garçon", de: "der Junge", pt: "o menino", it: "il ragazzo", ja: "男の子", zh: "男孩", ht: "tigason" } },
      { id: "girl", emoji: "👧", words: { en: "girl", es: "la niña", ru: "девочка", fr: "la fille", de: "das Mädchen", pt: "a menina", it: "la ragazza", ja: "女の子", zh: "女孩", ht: "tifi" } },
      { id: "friends", emoji: "🧑‍🤝‍🧑", words: { en: "friends", es: "los amigos", ru: "друзья", fr: "les amis", de: "die Freunde", pt: "os amigos", it: "gli amici", ja: "友達", zh: "朋友", ht: "zanmi" } },
    ],
  },
  {
    id: "sport",
    emoji: "⚽",
    color: "lime",
    names: { en: "Sport", es: "Deporte", ru: "Спорт", fr: "Sport", de: "Sport", pt: "Esporte", it: "Sport", ja: "スポーツ", zh: "运动" },
    items: [
      { id: "ball", emoji: "⚽", words: { en: "ball", es: "el balón", ru: "мяч", fr: "le ballon", de: "der Ball", pt: "a bola", it: "il pallone", ja: "ボール", zh: "球", ht: "boul" } },
      { id: "run", emoji: "🏃", words: { en: "run", es: "correr", ru: "бегать", fr: "courir", de: "laufen", pt: "correr", it: "correre", ja: "走る", zh: "跑步", ht: "kouri" } },
      { id: "swim", emoji: "🏊", words: { en: "swim", es: "nadar", ru: "плавать", fr: "nager", de: "schwimmen", pt: "nadar", it: "nuotare", ja: "泳ぐ", zh: "游泳", ht: "naje" } },
      { id: "jump", emoji: "🤸", words: { en: "jump", es: "saltar", ru: "прыгать", fr: "sauter", de: "springen", pt: "pular", it: "saltare", ja: "跳ぶ", zh: "跳", ht: "sote" } },
      { id: "dance", emoji: "💃", words: { en: "dance", es: "bailar", ru: "танцевать", fr: "danser", de: "tanzen", pt: "dançar", it: "ballare", ja: "踊る", zh: "跳舞", ht: "danse" } },
      { id: "basketball", emoji: "🏀", words: { en: "basketball", es: "el baloncesto", ru: "баскетбол", fr: "le basket", de: "der Basketball", pt: "o basquete", it: "il basket", ja: "バスケ", zh: "篮球", ht: "baskètbòl" } },
      { id: "tennis", emoji: "🎾", words: { en: "tennis", es: "el tenis", ru: "теннис", fr: "le tennis", de: "das Tennis", pt: "o tênis", it: "il tennis", ja: "テニス", zh: "网球", ht: "tenis" } },
      { id: "ski", emoji: "⛷️", words: { en: "ski", es: "esquiar", ru: "кататься на лыжах", fr: "skier", de: "Ski fahren", pt: "esquiar", it: "sciare", ja: "スキー", zh: "滑雪", ht: "ski" } },
    ],
  },
  {
    id: "health",
    emoji: "🩺",
    color: "coral",
    names: { en: "Health", es: "Salud", ru: "Здоровье", fr: "Santé", de: "Gesundheit", pt: "Saúde", it: "Salute", ja: "健康", zh: "健康" },
    items: [
      { id: "doctor", emoji: "🧑‍⚕️", words: { en: "doctor", es: "el médico", ru: "врач", fr: "le médecin", de: "der Arzt", pt: "o médico", it: "il medico", ja: "お医者さん", zh: "医生", ht: "doktè" } },
      { id: "medicine", emoji: "💊", words: { en: "medicine", es: "la medicina", ru: "лекарство", fr: "le médicament", de: "die Medizin", pt: "o remédio", it: "la medicina", ja: "薬", zh: "药", ht: "medikaman" } },
      { id: "hospital", emoji: "🏥", words: { en: "hospital", es: "el hospital", ru: "больница", fr: "l'hôpital", de: "das Krankenhaus", pt: "o hospital", it: "l'ospedale", ja: "病院", zh: "医院", ht: "lopital" } },
      { id: "sleep", emoji: "😴", words: { en: "sleep", es: "dormir", ru: "спать", fr: "dormir", de: "schlafen", pt: "dormir", it: "dormire", ja: "寝る", zh: "睡觉", ht: "dòmi" } },
      { id: "eat", emoji: "🍽️", words: { en: "eat", es: "comer", ru: "есть", fr: "manger", de: "essen", pt: "comer", it: "mangiare", ja: "食べる", zh: "吃饭", ht: "manje" } },
      { id: "drink", emoji: "🥤", words: { en: "drink", es: "beber", ru: "пить", fr: "boire", de: "trinken", pt: "beber", it: "bere", ja: "飲む", zh: "喝", ht: "bwè" } },
      { id: "wash", emoji: "🧼", words: { en: "wash", es: "lavar", ru: "мыть", fr: "laver", de: "waschen", pt: "lavar", it: "lavare", ja: "洗う", zh: "洗", ht: "lave" } },
      { id: "tooth-brush", emoji: "🪥", words: { en: "toothbrush", es: "el cepillo", ru: "зубная щётка", fr: "la brosse à dents", de: "die Zahnbürste", pt: "a escova", it: "lo spazzolino", ja: "歯ブラシ", zh: "牙刷", ht: "bwòs dan" } },
    ],
  },
  {
    id: "nature",
    emoji: "🌳",
    color: "mint",
    names: { en: "Nature", es: "Naturaleza", ru: "Природа", fr: "Nature", de: "Natur", pt: "Natureza", it: "Natura", ja: "自然", zh: "自然" },
    items: [
      { id: "sun", emoji: "☀️", words: { en: "sun", es: "el sol", ru: "солнце", fr: "le soleil", de: "die Sonne", pt: "o sol", it: "il sole", ja: "太陽", zh: "太阳", ht: "solèy" } },
      { id: "moon", emoji: "🌙", words: { en: "moon", es: "la luna", ru: "луна", fr: "la lune", de: "der Mond", pt: "a lua", it: "la luna", ja: "月", zh: "月亮", ht: "lalin" } },
      { id: "tree", emoji: "🌳", words: { en: "tree", es: "el árbol", ru: "дерево", fr: "l'arbre", de: "der Baum", pt: "a árvore", it: "l'albero", ja: "木", zh: "树", ht: "pyebwa" } },
      { id: "flower", emoji: "🌸", words: { en: "flower", es: "la flor", ru: "цветок", fr: "la fleur", de: "die Blume", pt: "a flor", it: "il fiore", ja: "花", zh: "花", ht: "flè" } },
      { id: "rain", emoji: "🌧️", words: { en: "rain", es: "la lluvia", ru: "дождь", fr: "la pluie", de: "der Regen", pt: "a chuva", it: "la pioggia", ja: "雨", zh: "雨", ht: "lapli" } },
      { id: "snow", emoji: "❄️", words: { en: "snow", es: "la nieve", ru: "снег", fr: "la neige", de: "der Schnee", pt: "a neve", it: "la neve", ja: "雪", zh: "雪", ht: "nèj" } },
      { id: "mountain", emoji: "⛰️", words: { en: "mountain", es: "la montaña", ru: "гора", fr: "la montagne", de: "der Berg", pt: "a montanha", it: "la montagna", ja: "山", zh: "山", ht: "mòn" } },
      { id: "sea", emoji: "🌊", words: { en: "sea", es: "el mar", ru: "море", fr: "la mer", de: "das Meer", pt: "o mar", it: "il mare", ja: "海", zh: "大海", ht: "lanmè" } },
      { id: "fire", emoji: "🔥", words: { en: "fire", es: "el fuego", ru: "огонь", fr: "le feu", de: "das Feuer", pt: "o fogo", it: "il fuoco", ja: "火", zh: "火", ht: "dife" } },
      { id: "star", emoji: "⭐", words: { en: "star", es: "la estrella", ru: "звезда", fr: "l'étoile", de: "der Stern", pt: "a estrela", it: "la stella", ja: "星", zh: "星星", ht: "zetwal" } },
    ],
  },
  {
    id: "work",
    emoji: "💼",
    color: "violet",
    names: { en: "Work", es: "Trabajo", ru: "Работа", fr: "Travail", de: "Arbeit", pt: "Trabalho", it: "Lavoro", ja: "仕事", zh: "工作" },
    items: [
      { id: "computer", emoji: "💻", words: { en: "computer", es: "el ordenador", ru: "компьютер", fr: "l'ordinateur", de: "der Computer", pt: "o computador", it: "il computer", ja: "パソコン", zh: "电脑", ht: "òdinatè" } },
      { id: "pen", emoji: "🖊️", words: { en: "pen", es: "el bolígrafo", ru: "ручка", fr: "le stylo", de: "der Stift", pt: "a caneta", it: "la penna", ja: "ペン", zh: "笔", ht: "plim" } },
      { id: "paper", emoji: "📄", words: { en: "paper", es: "el papel", ru: "бумага", fr: "le papier", de: "das Papier", pt: "o papel", it: "la carta", ja: "紙", zh: "纸", ht: "papye" } },
      { id: "money", emoji: "💰", words: { en: "money", es: "el dinero", ru: "деньги", fr: "l'argent", de: "das Geld", pt: "o dinheiro", it: "i soldi", ja: "お金", zh: "钱", ht: "lajan" } },
      { id: "teacher", emoji: "🧑‍🏫", words: { en: "teacher", es: "el profesor", ru: "учитель", fr: "le professeur", de: "der Lehrer", pt: "o professor", it: "l'insegnante", ja: "先生", zh: "老师", ht: "pwofesè" } },
      { id: "farmer", emoji: "🧑‍🌾", words: { en: "farmer", es: "el agricultor", ru: "фермер", fr: "le fermier", de: "der Bauer", pt: "o agricultor", it: "il contadino", ja: "農家", zh: "农民", ht: "kiltivatè" } },
      { id: "cook", emoji: "🧑‍🍳", words: { en: "cook", es: "el cocinero", ru: "повар", fr: "le cuisinier", de: "der Koch", pt: "o cozinheiro", it: "il cuoco", ja: "コックさん", zh: "厨师", ht: "kizinye" } },
      { id: "shop", emoji: "🏪", words: { en: "shop", es: "la tienda", ru: "магазин", fr: "le magasin", de: "der Laden", pt: "a loja", it: "il negozio", ja: "お店", zh: "商店", ht: "boutik" } },
    ],
  },

  /* ───────── Authentic Phase 1A sets (Rough-and-Ready Dozens, meeting-ordered) ───────── */
  {
    id: "colors",
    emoji: "🎨",
    meeting: 7,
    names: { en: "Colors" },
    color: "coral",
    items: [
      { id: "color-red", emoji: "🟥", meeting: 7, words: { en: "red", es: "rojo", ru: "красный", fr: "rouge", de: "rot", pt: "vermelho", it: "rosso", ja: "赤", zh: "红色", ht: "wouj" } },
      { id: "color-blue", emoji: "🟦", meeting: 7, words: { en: "blue", es: "azul", ru: "синий", fr: "bleu", de: "blau", pt: "azul", it: "blu", ja: "青", zh: "蓝色", ht: "ble" } },
      { id: "color-yellow", emoji: "🟨", meeting: 7, words: { en: "yellow", es: "amarillo", ru: "жёлтый", fr: "jaune", de: "gelb", pt: "amarelo", it: "giallo", ja: "黄色", zh: "黄色", ht: "jòn" } },
      { id: "color-green", emoji: "🟩", meeting: 7, words: { en: "green", es: "verde", ru: "зелёный", fr: "vert", de: "grün", pt: "verde", it: "verde", ja: "緑", zh: "绿色", ht: "vèt" } },
      { id: "color-white", emoji: "⬜", meeting: 7, words: { en: "white", es: "blanco", ru: "белый", fr: "blanc", de: "weiß", pt: "branco", it: "bianco", ja: "白", zh: "白色", ht: "blan" } },
      { id: "color-black", emoji: "⬛", meeting: 7, words: { en: "black", es: "negro", ru: "чёрный", fr: "noir", de: "schwarz", pt: "preto", it: "nero", ja: "黒", zh: "黑色", ht: "nwa" } },
      { id: "color-brown", emoji: "🟫", meeting: 7, words: { en: "brown", es: "marrón", ru: "коричневый", fr: "marron", de: "braun", pt: "marrom", it: "marrone", ja: "茶色", zh: "棕色", ht: "mawon" } },
      { id: "color-orange", emoji: "🟧", meeting: 7, words: { en: "orange", es: "naranja", ru: "оранжевый", fr: "orange", de: "orange", pt: "laranja", it: "arancione", ja: "オレンジ", zh: "橙色", ht: "zoranj" } },
      { id: "color-pink", emoji: "🩷", meeting: 7, words: { en: "pink", es: "rosa", ru: "розовый", fr: "rose", de: "rosa", pt: "rosa", it: "rosa", ja: "ピンク", zh: "粉色", ht: "woz" } },
      { id: "color-purple", emoji: "🟪", meeting: 7, words: { en: "purple", es: "morado", ru: "фиолетовый", fr: "violet", de: "lila", pt: "roxo", it: "viola", ja: "紫", zh: "紫色", ht: "mov" } },
    ],
  },
  {
    id: "numbers",
    emoji: "🔢",
    meeting: 12,
    names: { en: "Numbers" },
    color: "lemon",
    items: [
      { id: "num-one", emoji: "1️⃣", meeting: 12, words: { en: "one", es: "uno", ru: "один", fr: "un", de: "eins", pt: "um", it: "uno", ja: "一", zh: "一", ht: "youn" } },
      { id: "num-two", emoji: "2️⃣", meeting: 12, words: { en: "two", es: "dos", ru: "два", fr: "deux", de: "zwei", pt: "dois", it: "due", ja: "二", zh: "二", ht: "de" } },
      { id: "num-three", emoji: "3️⃣", meeting: 12, words: { en: "three", es: "tres", ru: "три", fr: "trois", de: "drei", pt: "três", it: "tre", ja: "三", zh: "三", ht: "twa" } },
      { id: "num-four", emoji: "4️⃣", meeting: 12, words: { en: "four", es: "cuatro", ru: "четыре", fr: "quatre", de: "vier", pt: "quatro", it: "quattro", ja: "四", zh: "四", ht: "kat" } },
      { id: "num-five", emoji: "5️⃣", meeting: 12, words: { en: "five", es: "cinco", ru: "пять", fr: "cinq", de: "fünf", pt: "cinco", it: "cinque", ja: "五", zh: "五", ht: "senk" } },
      { id: "num-six", emoji: "6️⃣", meeting: 12, words: { en: "six", es: "seis", ru: "шесть", fr: "six", de: "sechs", pt: "seis", it: "sei", ja: "六", zh: "六", ht: "sis" } },
      { id: "num-seven", emoji: "7️⃣", meeting: 12, words: { en: "seven", es: "siete", ru: "семь", fr: "sept", de: "sieben", pt: "sete", it: "sette", ja: "七", zh: "七", ht: "sèt" } },
      { id: "num-eight", emoji: "8️⃣", meeting: 12, words: { en: "eight", es: "ocho", ru: "восемь", fr: "huit", de: "acht", pt: "oito", it: "otto", ja: "八", zh: "八", ht: "uit" } },
      { id: "num-nine", emoji: "9️⃣", meeting: 12, words: { en: "nine", es: "nueve", ru: "девять", fr: "neuf", de: "neun", pt: "nove", it: "nove", ja: "九", zh: "九", ht: "nèf" } },
      { id: "num-ten", emoji: "🔟", meeting: 12, words: { en: "ten", es: "diez", ru: "десять", fr: "dix", de: "zehn", pt: "dez", it: "dieci", ja: "十", zh: "十", ht: "dis" } },
    ],
  },
  {
    id: "clothing",
    emoji: "👕",
    meeting: 9,
    names: { en: "Clothing" },
    color: "violet",
    items: [
      { id: "cloth-shirt", emoji: "👕", meeting: 9, words: { en: "shirt", es: "la camisa", ru: "рубашка", fr: "la chemise", de: "das Hemd", pt: "a camisa", it: "la camicia", ja: "シャツ", zh: "衬衫", ht: "chemiz" } },
      { id: "cloth-pants", emoji: "👖", meeting: 9, words: { en: "pants", es: "los pantalones", ru: "штаны", fr: "le pantalon", de: "die Hose", pt: "a calça", it: "i pantaloni", ja: "ズボン", zh: "裤子", ht: "pantalon" } },
      { id: "cloth-shoes", emoji: "👟", meeting: 9, words: { en: "shoes", es: "los zapatos", ru: "туфли", fr: "les chaussures", de: "die Schuhe", pt: "os sapatos", it: "le scarpe", ja: "靴", zh: "鞋子", ht: "soulye" } },
      { id: "cloth-socks", emoji: "🧦", meeting: 9, words: { en: "socks", es: "los calcetines", ru: "носки", fr: "les chaussettes", de: "die Socken", pt: "as meias", it: "i calzini", ja: "靴下", zh: "袜子", ht: "choset" } },
      { id: "cloth-hat", emoji: "🧢", meeting: 9, words: { en: "hat", es: "el sombrero", ru: "шапка", fr: "le chapeau", de: "der Hut", pt: "o chapéu", it: "il cappello", ja: "帽子", zh: "帽子", ht: "chapo" } },
      { id: "cloth-coat", emoji: "🧥", meeting: 9, words: { en: "coat", es: "el abrigo", ru: "пальто", fr: "le manteau", de: "der Mantel", pt: "o casaco", it: "il cappotto", ja: "コート", zh: "外套", ht: "manto" } },
      { id: "cloth-dress", emoji: "👗", meeting: 9, words: { en: "dress", es: "el vestido", ru: "платье", fr: "la robe", de: "das Kleid", pt: "o vestido", it: "il vestito", ja: "ワンピース", zh: "裙子", ht: "wòb" } },
      { id: "cloth-scarf", emoji: "🧣", meeting: 9, words: { en: "scarf", es: "la bufanda", ru: "шарф", fr: "l'écharpe", de: "der Schal", pt: "o cachecol", it: "la sciarpa", ja: "マフラー", zh: "围巾", ht: "foula" } },
      { id: "cloth-gloves", emoji: "🧤", meeting: 9, words: { en: "gloves", es: "los guantes", ru: "перчатки", fr: "les gants", de: "die Handschuhe", pt: "as luvas", it: "i guanti", ja: "手袋", zh: "手套", ht: "gan" } },
      { id: "cloth-jacket", emoji: "🧥", meeting: 9, words: { en: "jacket", es: "la chaqueta", ru: "куртка", fr: "la veste", de: "die Jacke", pt: "a jaqueta", it: "la giacca", ja: "ジャケット", zh: "夹克", ht: "jakèt" } },
    ],
  },
  {
    id: "prepositions",
    emoji: "📍",
    meeting: 4,
    names: { en: "Where things are" },
    color: "mint",
    items: [
      { id: "prep-on", emoji: "⬆️", meeting: 4, words: { en: "on", es: "encima de", ru: "на", fr: "sur", de: "auf", pt: "em cima de", it: "su", ja: "上", zh: "上面", ht: "sou" } },
      { id: "prep-under", emoji: "⬇️", meeting: 4, words: { en: "under", es: "debajo de", ru: "под", fr: "sous", de: "unter", pt: "embaixo de", it: "sotto", ja: "下", zh: "下面", ht: "anba" } },
      { id: "prep-in", emoji: "📥", meeting: 4, words: { en: "in", es: "dentro de", ru: "в", fr: "dans", de: "in", pt: "dentro de", it: "dentro", ja: "中", zh: "里面", ht: "nan" } },
      { id: "prep-behind", emoji: "🔙", meeting: 4, words: { en: "behind", es: "detrás de", ru: "за", fr: "derrière", de: "hinter", pt: "atrás de", it: "dietro", ja: "後ろ", zh: "后面", ht: "dèyè" } },
      { id: "prep-infront", emoji: "🔜", meeting: 4, words: { en: "in front of", es: "delante de", ru: "перед", fr: "devant", de: "vor", pt: "na frente de", it: "davanti a", ja: "前", zh: "前面", ht: "devan" } },
      { id: "prep-above", emoji: "🔝", meeting: 4, words: { en: "above", es: "arriba de", ru: "над", fr: "au-dessus de", de: "über", pt: "acima de", it: "sopra", ja: "上の方", zh: "上方", ht: "anwo" } },
      { id: "prep-beside", emoji: "↔️", meeting: 4, words: { en: "beside", es: "al lado de", ru: "рядом", fr: "à côté de", de: "neben", pt: "ao lado de", it: "accanto a", ja: "横", zh: "旁边", ht: "akote" } },
      { id: "prep-between", emoji: "🔀", meeting: 4, words: { en: "between", es: "entre", ru: "между", fr: "entre", de: "zwischen", pt: "entre", it: "tra", ja: "間", zh: "中间", ht: "ant" } },
    ],
  },
  {
    id: "emotions",
    emoji: "😀",
    meeting: 11,
    names: { en: "Feelings" },
    color: "orange",
    items: [
      { id: "emo-happy", emoji: "😀", meeting: 11, words: { en: "happy", es: "feliz", ru: "счастливый", fr: "content", de: "glücklich", pt: "feliz", it: "felice", ja: "嬉しい", zh: "开心", ht: "kontan" } },
      { id: "emo-sad", emoji: "😢", meeting: 11, words: { en: "sad", es: "triste", ru: "грустный", fr: "triste", de: "traurig", pt: "triste", it: "triste", ja: "悲しい", zh: "难过", ht: "tris" } },
      { id: "emo-angry", emoji: "😠", meeting: 11, words: { en: "angry", es: "enojado", ru: "сердитый", fr: "fâché", de: "wütend", pt: "bravo", it: "arrabbiato", ja: "怒る", zh: "生气", ht: "fache" } },
      { id: "emo-surprised", emoji: "😲", meeting: 11, words: { en: "surprised", es: "sorprendido", ru: "удивлённый", fr: "surpris", de: "überrascht", pt: "surpreso", it: "sorpreso", ja: "びっくり", zh: "惊讶", ht: "sezi" } },
      { id: "emo-scared", emoji: "😨", meeting: 11, words: { en: "scared", es: "asustado", ru: "испуганный", fr: "effrayé", de: "ängstlich", pt: "assustado", it: "spaventato", ja: "怖い", zh: "害怕", ht: "pè" } },
      { id: "emo-sleepy", emoji: "😪", meeting: 11, words: { en: "sleepy", es: "soñoliento", ru: "сонный", fr: "endormi", de: "müde", pt: "sonolento", it: "assonnato", ja: "眠い", zh: "困", ht: "dòmi nan je" } },
      { id: "emo-crying", emoji: "😭", meeting: 11, words: { en: "crying", es: "llorando", ru: "плачет", fr: "pleurer", de: "weinen", pt: "chorando", it: "piangere", ja: "泣く", zh: "哭", ht: "kriye" } },
      { id: "emo-laughing", emoji: "😂", meeting: 11, words: { en: "laughing", es: "riendo", ru: "смеётся", fr: "rire", de: "lachen", pt: "rindo", it: "ridere", ja: "笑う", zh: "笑", ht: "ri" } },
    ],
  },
  {
    id: "tableware",
    emoji: "🍴",
    meeting: 2,
    names: { en: "Kitchen & table" },
    color: "lime",
    items: [
      { id: "tbl-knife", emoji: "🔪", meeting: 2, words: { en: "knife", es: "el cuchillo", ru: "нож", fr: "le couteau", de: "das Messer", pt: "a faca", it: "il coltello", ja: "ナイフ", zh: "刀", ht: "kouto" } },
      { id: "tbl-fork", emoji: "🍴", meeting: 2, words: { en: "fork", es: "el tenedor", ru: "вилка", fr: "la fourchette", de: "die Gabel", pt: "o garfo", it: "la forchetta", ja: "フォーク", zh: "叉子", ht: "fouchèt" } },
      { id: "tbl-spoon", emoji: "🥄", meeting: 2, words: { en: "spoon", es: "la cuchara", ru: "ложка", fr: "la cuillère", de: "der Löffel", pt: "a colher", it: "il cucchiaio", ja: "スプーン", zh: "勺子", ht: "kiyè" } },
      { id: "tbl-plate", emoji: "🍽️", meeting: 2, words: { en: "plate", es: "el plato", ru: "тарелка", fr: "l'assiette", de: "der Teller", pt: "o prato", it: "il piatto", ja: "お皿", zh: "盘子", ht: "asyèt" } },
      { id: "tbl-bowl", emoji: "🥣", meeting: 2, words: { en: "bowl", es: "el tazón", ru: "миска", fr: "le bol", de: "die Schüssel", pt: "a tigela", it: "la ciotola", ja: "お椀", zh: "碗", ht: "bòl" } },
      { id: "tbl-pot", emoji: "🍳", meeting: 2, words: { en: "pot", es: "la olla", ru: "кастрюля", fr: "la casserole", de: "der Topf", pt: "a panela", it: "la pentola", ja: "鍋", zh: "锅", ht: "chodyè" } },
    ],
  },
  {
    id: "tools",
    emoji: "🔧",
    meeting: 11,
    names: { en: "Tools" },
    color: "coral",
    items: [
      { id: "tool-hammer", emoji: "🔨", meeting: 11, words: { en: "hammer", es: "el martillo", ru: "молоток", fr: "le marteau", de: "der Hammer", pt: "o martelo", it: "il martello", ja: "金槌", zh: "锤子", ht: "mato" } },
      { id: "tool-saw", emoji: "🪚", meeting: 11, words: { en: "saw", es: "el serrucho", ru: "пила", fr: "la scie", de: "die Säge", pt: "o serrote", it: "la sega", ja: "のこぎり", zh: "锯子", ht: "si" } },
      { id: "tool-scissors", emoji: "✂️", meeting: 11, words: { en: "scissors", es: "las tijeras", ru: "ножницы", fr: "les ciseaux", de: "die Schere", pt: "a tesoura", it: "le forbici", ja: "はさみ", zh: "剪刀", ht: "sizo" } },
      { id: "tool-screwdriver", emoji: "🪛", meeting: 11, words: { en: "screwdriver", es: "el destornillador", ru: "отвёртка", fr: "le tournevis", de: "der Schraubenzieher", pt: "a chave de fenda", it: "il cacciavite", ja: "ドライバー", zh: "螺丝刀", ht: "tounvis" } },
      { id: "tool-wrench", emoji: "🔧", meeting: 11, words: { en: "wrench", es: "la llave", ru: "гаечный ключ", fr: "la clé", de: "der Schraubenschlüssel", pt: "a chave inglesa", it: "la chiave inglese", ja: "レンチ", zh: "扳手", ht: "kle" } },
      { id: "tool-nail", emoji: "📌", meeting: 11, words: { en: "nail", es: "el clavo", ru: "гвоздь", fr: "le clou", de: "der Nagel", pt: "o prego", it: "il chiodo", ja: "釘", zh: "钉子", ht: "klou" } },
      { id: "tool-rope", emoji: "🪢", meeting: 11, words: { en: "rope", es: "la cuerda", ru: "верёвка", fr: "la corde", de: "das Seil", pt: "a corda", it: "la corda", ja: "ロープ", zh: "绳子", ht: "kòd" } },
    ],
  },
  {
    id: "room",
    emoji: "🚪",
    meeting: 3,
    names: { en: "Parts of the room" },
    color: "violet",
    items: [
      { id: "room-wall", emoji: "🧱", meeting: 3, words: { en: "wall", es: "la pared", ru: "стена", fr: "le mur", de: "die Wand", pt: "a parede", it: "la parete", ja: "壁", zh: "墙", ht: "miray" } },
      { id: "room-floor", emoji: "⬛", meeting: 3, words: { en: "floor", es: "el suelo", ru: "пол", fr: "le sol", de: "der Boden", pt: "o chão", it: "il pavimento", ja: "床", zh: "地板", ht: "atè" } },
      { id: "room-ceiling", emoji: "🔲", meeting: 3, words: { en: "ceiling", es: "el techo", ru: "потолок", fr: "le plafond", de: "die Decke", pt: "o teto", it: "il soffitto", ja: "天井", zh: "天花板", ht: "plafon" } },
      { id: "room-roof", emoji: "🏠", meeting: 3, words: { en: "roof", es: "el tejado", ru: "крыша", fr: "le toit", de: "das Dach", pt: "o telhado", it: "il tetto", ja: "屋根", zh: "屋顶", ht: "twati" } },
      { id: "room-stairs", emoji: "🪜", meeting: 3, words: { en: "stairs", es: "las escaleras", ru: "лестница", fr: "l'escalier", de: "die Treppe", pt: "a escada", it: "le scale", ja: "階段", zh: "楼梯", ht: "eskalye" } },
      { id: "room-shelf", emoji: "🗄️", meeting: 3, words: { en: "shelf", es: "el estante", ru: "полка", fr: "l'étagère", de: "das Regal", pt: "a prateleira", it: "lo scaffale", ja: "棚", zh: "架子", ht: "etajè" } },
    ],
  },
  {
    id: "rooms",
    emoji: "🏠",
    meeting: 8,
    names: { en: "Rooms of the house" },
    color: "mint",
    items: [
      { id: "rooms-kitchen", emoji: "🍳", meeting: 8, words: { en: "kitchen", es: "la cocina", ru: "кухня", fr: "la cuisine", de: "die Küche", pt: "a cozinha", it: "la cucina", ja: "台所", zh: "厨房", ht: "kizin" } },
      { id: "rooms-bedroom", emoji: "🛏️", meeting: 8, words: { en: "bedroom", es: "el dormitorio", ru: "спальня", fr: "la chambre", de: "das Schlafzimmer", pt: "o quarto", it: "la camera da letto", ja: "寝室", zh: "卧室", ht: "chanm" } },
      { id: "rooms-bathroom", emoji: "🚽", meeting: 8, words: { en: "bathroom", es: "el baño", ru: "ванная", fr: "la salle de bains", de: "das Badezimmer", pt: "o banheiro", it: "il bagno", ja: "お風呂", zh: "卫生间", ht: "twalèt" } },
      { id: "rooms-living", emoji: "🛋️", meeting: 8, words: { en: "living room", es: "la sala", ru: "гостиная", fr: "le salon", de: "das Wohnzimmer", pt: "a sala", it: "il soggiorno", ja: "居間", zh: "客厅", ht: "salon" } },
    ],
  },
  {
    id: "family-more",
    emoji: "👨‍👩‍👧",
    meeting: 5,
    names: { en: "More family" },
    color: "orange",
    items: [
      { id: "fam-son", emoji: "👦", meeting: 5, words: { en: "son", es: "el hijo", ru: "сын", fr: "le fils", de: "der Sohn", pt: "o filho", it: "il figlio", ja: "息子", zh: "儿子", ht: "pitit gason" } },
      { id: "fam-daughter", emoji: "👧", meeting: 5, words: { en: "daughter", es: "la hija", ru: "дочь", fr: "la fille", de: "die Tochter", pt: "a filha", it: "la figlia", ja: "娘", zh: "女儿", ht: "pitit fi" } },
      { id: "fam-brother", emoji: "👬", meeting: 5, words: { en: "brother", es: "el hermano", ru: "брат", fr: "le frère", de: "der Bruder", pt: "o irmão", it: "il fratello", ja: "兄弟", zh: "兄弟", ht: "frè" } },
      { id: "fam-sister", emoji: "👭", meeting: 5, words: { en: "sister", es: "la hermana", ru: "сестра", fr: "la sœur", de: "die Schwester", pt: "a irmã", it: "la sorella", ja: "姉妹", zh: "姐妹", ht: "sè" } },
      { id: "fam-husband", emoji: "🤵", meeting: 5, words: { en: "husband", es: "el esposo", ru: "муж", fr: "le mari", de: "der Mann", pt: "o marido", it: "il marito", ja: "夫", zh: "丈夫", ht: "mari" } },
      { id: "fam-wife", emoji: "👰", meeting: 5, words: { en: "wife", es: "la esposa", ru: "жена", fr: "la femme", de: "die Frau", pt: "a esposa", it: "la moglie", ja: "妻", zh: "妻子", ht: "madanm" } },
    ],
  },
  {
    id: "body-more",
    emoji: "🦵",
    meeting: 5,
    names: { en: "More body parts" },
    color: "lemon",
    items: [
      { id: "body-leg", emoji: "🦵", meeting: 5, words: { en: "leg", es: "la pierna", ru: "нога", fr: "la jambe", de: "das Bein", pt: "a perna", it: "la gamba", ja: "足", zh: "腿", ht: "janm" } },
      { id: "body-arm", emoji: "💪", meeting: 5, words: { en: "arm", es: "el brazo", ru: "рука", fr: "le bras", de: "der Arm", pt: "o braço", it: "il braccio", ja: "腕", zh: "手臂", ht: "bra" } },
      { id: "body-finger", emoji: "☝️", meeting: 5, words: { en: "finger", es: "el dedo", ru: "палец", fr: "le doigt", de: "der Finger", pt: "o dedo", it: "il dito", ja: "指", zh: "手指", ht: "dwèt" } },
      { id: "body-knee", emoji: "🦵", meeting: 5, words: { en: "knee", es: "la rodilla", ru: "колено", fr: "le genou", de: "das Knie", pt: "o joelho", it: "il ginocchio", ja: "膝", zh: "膝盖", ht: "jenou" } },
      { id: "body-shoulder", emoji: "🫱", meeting: 5, words: { en: "shoulder", es: "el hombro", ru: "плечо", fr: "l'épaule", de: "die Schulter", pt: "o ombro", it: "la spalla", ja: "肩", zh: "肩膀", ht: "zepòl" } },
      { id: "body-neck", emoji: "🧣", meeting: 5, words: { en: "neck", es: "el cuello", ru: "шея", fr: "le cou", de: "der Hals", pt: "o pescoço", it: "il collo", ja: "首", zh: "脖子", ht: "kou" } },
      { id: "body-back", emoji: "🔙", meeting: 5, words: { en: "back", es: "la espalda", ru: "спина", fr: "le dos", de: "der Rücken", pt: "as costas", it: "la schiena", ja: "背中", zh: "背", ht: "do" } },
      { id: "body-stomach", emoji: "🫃", meeting: 5, words: { en: "stomach", es: "el estómago", ru: "живот", fr: "le ventre", de: "der Bauch", pt: "a barriga", it: "la pancia", ja: "お腹", zh: "肚子", ht: "vant" } },
    ],
  },
  {
    id: "adjectives",
    emoji: "📏",
    meeting: 25,
    names: { en: "Describing words" },
    color: "lime",
    items: [
      { id: "adj-big", emoji: "🔼", meeting: 25, words: { en: "big", es: "grande", ru: "большой", fr: "grand", de: "groß", pt: "grande", it: "grande", ja: "大きい", zh: "大", ht: "gwo" } },
      { id: "adj-small", emoji: "🔽", meeting: 25, words: { en: "small", es: "pequeño", ru: "маленький", fr: "petit", de: "klein", pt: "pequeno", it: "piccolo", ja: "小さい", zh: "小", ht: "piti" } },
      { id: "adj-hot", emoji: "🥵", meeting: 25, words: { en: "hot", es: "caliente", ru: "горячий", fr: "chaud", de: "heiß", pt: "quente", it: "caldo", ja: "熱い", zh: "热", ht: "cho" } },
      { id: "adj-cold", emoji: "🥶", meeting: 25, words: { en: "cold", es: "frío", ru: "холодный", fr: "froid", de: "kalt", pt: "frio", it: "freddo", ja: "冷たい", zh: "冷", ht: "frèt" } },
      { id: "adj-old", emoji: "👴", meeting: 25, words: { en: "old", es: "viejo", ru: "старый", fr: "vieux", de: "alt", pt: "velho", it: "vecchio", ja: "古い", zh: "旧", ht: "vye" } },
      { id: "adj-new", emoji: "✨", meeting: 25, words: { en: "new", es: "nuevo", ru: "новый", fr: "neuf", de: "neu", pt: "novo", it: "nuovo", ja: "新しい", zh: "新", ht: "nèf" } },
      { id: "adj-long", emoji: "📏", meeting: 25, words: { en: "long", es: "largo", ru: "длинный", fr: "long", de: "lang", pt: "comprido", it: "lungo", ja: "長い", zh: "长", ht: "long" } },
      { id: "adj-short", emoji: "📐", meeting: 25, words: { en: "short", es: "corto", ru: "короткий", fr: "court", de: "kurz", pt: "curto", it: "corto", ja: "短い", zh: "短", ht: "kout" } },
      { id: "adj-heavy", emoji: "🏋️", meeting: 25, words: { en: "heavy", es: "pesado", ru: "тяжёлый", fr: "lourd", de: "schwer", pt: "pesado", it: "pesante", ja: "重い", zh: "重", ht: "lou" } },
      { id: "adj-fast", emoji: "💨", meeting: 25, words: { en: "fast", es: "rápido", ru: "быстрый", fr: "rapide", de: "schnell", pt: "rápido", it: "veloce", ja: "速い", zh: "快", ht: "vit" } },
    ],
  },
  {
    id: "states",
    emoji: "🤒",
    meeting: 19,
    names: { en: "How I feel (body)" },
    color: "coral",
    items: [
      { id: "state-hungry", emoji: "🍽️", meeting: 19, words: { en: "hungry", es: "hambriento", ru: "голодный", fr: "affamé", de: "hungrig", pt: "com fome", it: "affamato", ja: "お腹すいた", zh: "饿", ht: "grangou" } },
      { id: "state-thirsty", emoji: "💧", meeting: 19, words: { en: "thirsty", es: "sediento", ru: "жаждущий", fr: "assoiffé", de: "durstig", pt: "com sede", it: "assetato", ja: "喉乾いた", zh: "渴", ht: "swaf" } },
      { id: "state-tired", emoji: "😮‍💨", meeting: 19, words: { en: "tired", es: "cansado", ru: "усталый", fr: "fatigué", de: "müde", pt: "cansado", it: "stanco", ja: "疲れた", zh: "累", ht: "fatige" } },
      { id: "state-sick", emoji: "🤒", meeting: 19, words: { en: "sick", es: "enfermo", ru: "больной", fr: "malade", de: "krank", pt: "doente", it: "malato", ja: "病気", zh: "生病", ht: "malad" } },
      { id: "state-dirty", emoji: "🫧", meeting: 19, words: { en: "dirty", es: "sucio", ru: "грязный", fr: "sale", de: "schmutzig", pt: "sujo", it: "sporco", ja: "汚い", zh: "脏", ht: "sal" } },
      { id: "state-clean", emoji: "🧼", meeting: 19, words: { en: "clean", es: "limpio", ru: "чистый", fr: "propre", de: "sauber", pt: "limpo", it: "pulito", ja: "きれい", zh: "干净", ht: "pwòp" } },
    ],
  },
  {
    id: "insects",
    emoji: "🐛",
    meeting: 12,
    names: { en: "Insects & small creatures" },
    color: "mint",
    items: [
      { id: "bug-fly", emoji: "🪰", meeting: 12, words: { en: "fly", es: "la mosca", ru: "муха", fr: "la mouche", de: "die Fliege", pt: "a mosca", it: "la mosca", ja: "ハエ", zh: "苍蝇", ht: "mouch" } },
      { id: "bug-spider", emoji: "🕷️", meeting: 12, words: { en: "spider", es: "la araña", ru: "паук", fr: "l'araignée", de: "die Spinne", pt: "a aranha", it: "il ragno", ja: "クモ", zh: "蜘蛛", ht: "arenyen" } },
      { id: "bug-bee", emoji: "🐝", meeting: 12, words: { en: "bee", es: "la abeja", ru: "пчела", fr: "l'abeille", de: "die Biene", pt: "a abelha", it: "l'ape", ja: "ハチ", zh: "蜜蜂", ht: "myèl" } },
      { id: "bug-ant", emoji: "🐜", meeting: 12, words: { en: "ant", es: "la hormiga", ru: "муравей", fr: "la fourmi", de: "die Ameise", pt: "a formiga", it: "la formica", ja: "アリ", zh: "蚂蚁", ht: "foumi" } },
      { id: "bug-snake", emoji: "🐍", meeting: 12, words: { en: "snake", es: "la serpiente", ru: "змея", fr: "le serpent", de: "die Schlange", pt: "a cobra", it: "il serpente", ja: "ヘビ", zh: "蛇", ht: "koulèv" } },
    ],
  },
  {
    id: "animals-more",
    emoji: "🐘",
    meeting: 3,
    names: { en: "More animals" },
    color: "violet",
    items: [
      { id: "animal-duck", emoji: "🦆", meeting: 3, words: { en: "duck", es: "el pato", ru: "утка", fr: "le canard", de: "die Ente", pt: "o pato", it: "l'anatra", ja: "アヒル", zh: "鸭子", ht: "kanna" } },
      { id: "animal-goat", emoji: "🐐", meeting: 3, words: { en: "goat", es: "la cabra", ru: "коза", fr: "la chèvre", de: "die Ziege", pt: "a cabra", it: "la capra", ja: "ヤギ", zh: "山羊", ht: "kabrit" } },
      { id: "animal-pig", emoji: "🐷", meeting: 3, words: { en: "pig", es: "el cerdo", ru: "свинья", fr: "le cochon", de: "das Schwein", pt: "o porco", it: "il maiale", ja: "ブタ", zh: "猪", ht: "kochon" } },
      { id: "animal-elephant", emoji: "🐘", meeting: 3, words: { en: "elephant", es: "el elefante", ru: "слон", fr: "l'éléphant", de: "der Elefant", pt: "o elefante", it: "l'elefante", ja: "ゾウ", zh: "大象", ht: "elefan" } },
      { id: "animal-lion", emoji: "🦁", meeting: 3, words: { en: "lion", es: "el león", ru: "лев", fr: "le lion", de: "der Löwe", pt: "o leão", it: "il leone", ja: "ライオン", zh: "狮子", ht: "lyon" } },
      { id: "animal-goose", emoji: "🪿", meeting: 3, words: { en: "goose", es: "el ganso", ru: "гусь", fr: "l'oie", de: "die Gans", pt: "o ganso", it: "l'oca", ja: "ガチョウ", zh: "鹅", ht: "zwa" } },
    ],
  },
  {
    id: "nature-more",
    emoji: "🌳",
    meeting: 14,
    names: { en: "The outdoors" },
    color: "lime",
    items: [
      { id: "nat-cloud", emoji: "☁️", meeting: 14, words: { en: "cloud", es: "la nube", ru: "облако", fr: "le nuage", de: "die Wolke", pt: "a nuvem", it: "la nuvola", ja: "雲", zh: "云", ht: "nyaj" } },
      { id: "nat-grass", emoji: "🌿", meeting: 14, words: { en: "grass", es: "el césped", ru: "трава", fr: "l'herbe", de: "das Gras", pt: "a grama", it: "l'erba", ja: "草", zh: "草", ht: "zèb" } },
      { id: "nat-forest", emoji: "🌲", meeting: 14, words: { en: "forest", es: "el bosque", ru: "лес", fr: "la forêt", de: "der Wald", pt: "a floresta", it: "la foresta", ja: "森", zh: "森林", ht: "rakbwa" } },
      { id: "nat-river", emoji: "🏞️", meeting: 14, words: { en: "river", es: "el río", ru: "река", fr: "la rivière", de: "der Fluss", pt: "o rio", it: "il fiume", ja: "川", zh: "河", ht: "rivyè" } },
      { id: "nat-hill", emoji: "⛰️", meeting: 14, words: { en: "hill", es: "la colina", ru: "холм", fr: "la colline", de: "der Hügel", pt: "a colina", it: "la collina", ja: "丘", zh: "山丘", ht: "mòn" } },
      { id: "nat-lake", emoji: "🏞️", meeting: 14, words: { en: "lake", es: "el lago", ru: "озеро", fr: "le lac", de: "der See", pt: "o lago", it: "il lago", ja: "湖", zh: "湖", ht: "lak" } },
      { id: "nat-sky", emoji: "🌌", meeting: 14, words: { en: "sky", es: "el cielo", ru: "небо", fr: "le ciel", de: "der Himmel", pt: "o céu", it: "il cielo", ja: "空", zh: "天空", ht: "syèl" } },
    ],
  },
  {
    id: "drinks-more",
    emoji: "🥤",
    meeting: 8,
    names: { en: "More drinks" },
    color: "orange",
    items: [
      { id: "drink-tea", emoji: "🍵", meeting: 8, words: { en: "tea", es: "el té", ru: "чай", fr: "le thé", de: "der Tee", pt: "o chá", it: "il tè", ja: "お茶", zh: "茶", ht: "te" } },
      { id: "drink-juice", emoji: "🧃", meeting: 8, words: { en: "juice", es: "el jugo", ru: "сок", fr: "le jus", de: "der Saft", pt: "o suco", it: "il succo", ja: "ジュース", zh: "果汁", ht: "ji" } },
    ],
  },
  {
    id: "verbs",
    emoji: "🏃",
    meeting: 33,
    names: { en: "Action words" },
    color: "lemon",
    items: [
      { id: "verb-pour", emoji: "🫗", meeting: 33, words: { en: "pour", es: "verter", ru: "наливать", fr: "verser", de: "gießen", pt: "despejar", it: "versare", ja: "注ぐ", zh: "倒", ht: "vide" } },
      { id: "verb-cut", emoji: "🔪", meeting: 33, words: { en: "cut", es: "cortar", ru: "резать", fr: "couper", de: "schneiden", pt: "cortar", it: "tagliare", ja: "切る", zh: "切", ht: "koupe" } },
      { id: "verb-throw", emoji: "🤾", meeting: 33, words: { en: "throw", es: "lanzar", ru: "бросать", fr: "lancer", de: "werfen", pt: "jogar", it: "lanciare", ja: "投げる", zh: "扔", ht: "voye" } },
      { id: "verb-catch", emoji: "🧤", meeting: 33, words: { en: "catch", es: "atrapar", ru: "ловить", fr: "attraper", de: "fangen", pt: "pegar", it: "prendere", ja: "受け取る", zh: "接", ht: "trape" } },
      { id: "verb-push", emoji: "🫷", meeting: 33, words: { en: "push", es: "empujar", ru: "толкать", fr: "pousser", de: "schieben", pt: "empurrar", it: "spingere", ja: "押す", zh: "推", ht: "pouse" } },
      { id: "verb-pull", emoji: "🫸", meeting: 33, words: { en: "pull", es: "jalar", ru: "тянуть", fr: "tirer", de: "ziehen", pt: "puxar", it: "tirare", ja: "引く", zh: "拉", ht: "rale" } },
      { id: "verb-turn", emoji: "🔄", meeting: 33, words: { en: "turn", es: "girar", ru: "поворачивать", fr: "tourner", de: "drehen", pt: "virar", it: "girare", ja: "回す", zh: "转", ht: "vire" } },
      { id: "verb-read", emoji: "📖", meeting: 33, words: { en: "read", es: "leer", ru: "читать", fr: "lire", de: "lesen", pt: "ler", it: "leggere", ja: "読む", zh: "读", ht: "li" } },
      { id: "verb-write", emoji: "✍️", meeting: 33, words: { en: "write", es: "escribir", ru: "писать", fr: "écrire", de: "schreiben", pt: "escrever", it: "scrivere", ja: "書く", zh: "写", ht: "ekri" } },
      { id: "verb-draw", emoji: "🖍️", meeting: 33, words: { en: "draw", es: "dibujar", ru: "рисовать", fr: "dessiner", de: "malen", pt: "desenhar", it: "disegnare", ja: "描く", zh: "画", ht: "desine" } },
      { id: "verb-look", emoji: "👀", meeting: 33, words: { en: "look", es: "mirar", ru: "смотреть", fr: "regarder", de: "schauen", pt: "olhar", it: "guardare", ja: "見る", zh: "看", ht: "gade" } },
      { id: "verb-hold", emoji: "🤲", meeting: 33, words: { en: "hold", es: "sostener", ru: "держать", fr: "tenir", de: "halten", pt: "segurar", it: "tenere", ja: "持つ", zh: "拿", ht: "kenbe" } },
      { id: "verb-carry", emoji: "🛍️", meeting: 33, words: { en: "carry", es: "cargar", ru: "нести", fr: "porter", de: "tragen", pt: "carregar", it: "portare", ja: "運ぶ", zh: "搬", ht: "pote" } },
      { id: "verb-climb", emoji: "🧗", meeting: 33, words: { en: "climb", es: "trepar", ru: "лезть", fr: "grimper", de: "klettern", pt: "subir", it: "arrampicarsi", ja: "登る", zh: "爬", ht: "monte" } },
      { id: "verb-ride", emoji: "🐎", meeting: 33, words: { en: "ride", es: "montar", ru: "ехать", fr: "monter", de: "reiten", pt: "andar", it: "cavalcare", ja: "乗る", zh: "骑", ht: "monte" } },
      { id: "verb-see", emoji: "👁️", meeting: 33, words: { en: "see", es: "ver", ru: "видеть", fr: "voir", de: "sehen", pt: "ver", it: "vedere", ja: "見える", zh: "看见", ht: "wè" } },
      { id: "verb-want", emoji: "🙏", meeting: 33, words: { en: "want", es: "querer", ru: "хотеть", fr: "vouloir", de: "wollen", pt: "querer", it: "volere", ja: "欲しい", zh: "要", ht: "vle" } },
      { id: "verb-listen", emoji: "👂", meeting: 33, words: { en: "listen", es: "escuchar", ru: "слушать", fr: "écouter", de: "hören", pt: "escutar", it: "ascoltare", ja: "聞く", zh: "听", ht: "koute" } },
      { id: "verb-touch", emoji: "👆", meeting: 33, words: { en: "touch", es: "tocar", ru: "трогать", fr: "toucher", de: "berühren", pt: "tocar", it: "toccare", ja: "触る", zh: "摸", ht: "manyen" } },
      { id: "verb-kick", emoji: "🦵", meeting: 33, words: { en: "kick", es: "patear", ru: "пинать", fr: "donner un coup de pied", de: "treten", pt: "chutar", it: "calciare", ja: "蹴る", zh: "踢", ht: "tape" } },
    ],
  },
];

export const domainById = (id: string) => VOCAB_DOMAINS.find((d) => d.id === id);

/** TPR-style action commands for the listening trainer (Phase 1 "Total Physical Response") */
export const TPR_COMMANDS: { id: string; emoji: string; words: Partial<Record<string, string>> }[] = [
  { id: "stand", emoji: "🧍", words: { en: "Stand up!", es: "¡Levántate!", ru: "Встань!", fr: "Lève-toi !", de: "Steh auf!", pt: "Levanta-te!", it: "Alzati!", ja: "立って！", zh: "站起来！", ht: "Kanpe!" } },
  { id: "sit", emoji: "🪑", words: { en: "Sit down!", es: "¡Siéntate!", ru: "Сядь!", fr: "Assieds-toi !", de: "Setz dich!", pt: "Senta-te!", it: "Siediti!", ja: "座って！", zh: "坐下！", ht: "Chita!" } },
  { id: "point", emoji: "👉", words: { en: "Point!", es: "¡Señala!", ru: "Покажи!", fr: "Montre !", de: "Zeig!", pt: "Aponta!", it: "Indica!", ja: "指さして！", zh: "指一指！", ht: "Lonje dwèt ou!" } },
  { id: "take", emoji: "🤲", words: { en: "Take it!", es: "¡Toma!", ru: "Возьми!", fr: "Prends !", de: "Nimm!", pt: "Pega!", it: "Prendi!", ja: "取って！", zh: "拿着！", ht: "Pran l!" } },
  { id: "give", emoji: "🫴", words: { en: "Give it to me!", es: "¡Dame!", ru: "Дай!", fr: "Donne !", de: "Gib!", pt: "Dá!", it: "Dammi!", ja: "ちょうだい！", zh: "给我！", ht: "Ban m li!" } },
  { id: "open", emoji: "📂", words: { en: "Open it!", es: "¡Abre!", ru: "Открой!", fr: "Ouvre !", de: "Öffne!", pt: "Abre!", it: "Apri!", ja: "開けて！", zh: "打开！", ht: "Louvri l!" } },
  { id: "close", emoji: "📁", words: { en: "Close it!", es: "¡Cierra!", ru: "Закрой!", fr: "Ferme !", de: "Schließ!", pt: "Fecha!", it: "Chiudi!", ja: "閉めて！", zh: "关上！", ht: "Fèmen l!" } },
  { id: "walk", emoji: "🚶", words: { en: "Walk!", es: "¡Camina!", ru: "Иди!", fr: "Marche !", de: "Geh!", pt: "Anda!", it: "Cammina!", ja: "歩いて！", zh: "走！", ht: "Mache!" } },
];
