import type { VocabDomain } from "./types";

/**
 * Digital picture-card decks — the heart of GPA Phase 1–2 practice.
 * Like the nurturer's photo cards: meaning is carried by the IMAGE,
 * never by translation into the grower's language.
 */
export const VOCAB_DOMAINS: VocabDomain[] = [
  {
    id: "food",
    emoji: "🍎",
    color: "violet",
    names: { en: "Food", es: "Comida", ru: "Еда", fr: "Nourriture", de: "Essen", pt: "Comida", it: "Cibo", ja: "食べ物", zh: "食物" },
    items: [
      { id: "apple", emoji: "🍎", words: { es: "la manzana", ru: "яблоко", fr: "la pomme", de: "der Apfel", pt: "a maçã", it: "la mela", ja: "りんご", zh: "苹果" } },
      { id: "bread", emoji: "🍞", words: { es: "el pan", ru: "хлеб", fr: "le pain", de: "das Brot", pt: "o pão", it: "il pane", ja: "パン", zh: "面包" } },
      { id: "milk", emoji: "🥛", words: { es: "la leche", ru: "молоко", fr: "le lait", de: "die Milch", pt: "o leite", it: "il latte", ja: "牛乳", zh: "牛奶" } },
      { id: "egg", emoji: "🥚", words: { es: "el huevo", ru: "яйцо", fr: "l'œuf", de: "das Ei", pt: "o ovo", it: "l'uovo", ja: "卵", zh: "鸡蛋" } },
      { id: "fish", emoji: "🐟", words: { es: "el pescado", ru: "рыба", fr: "le poisson", de: "der Fisch", pt: "o peixe", it: "il pesce", ja: "魚", zh: "鱼" } },
      { id: "cheese", emoji: "🧀", words: { es: "el queso", ru: "сыр", fr: "le fromage", de: "der Käse", pt: "o queijo", it: "il formaggio", ja: "チーズ", zh: "奶酪" } },
      { id: "water", emoji: "💧", words: { es: "el agua", ru: "вода", fr: "l'eau", de: "das Wasser", pt: "a água", it: "l'acqua", ja: "水", zh: "水" } },
      { id: "coffee", emoji: "☕", words: { es: "el café", ru: "кофе", fr: "le café", de: "der Kaffee", pt: "o café", it: "il caffè", ja: "コーヒー", zh: "咖啡" } },
      { id: "rice", emoji: "🍚", words: { es: "el arroz", ru: "рис", fr: "le riz", de: "der Reis", pt: "o arroz", it: "il riso", ja: "ご飯", zh: "米饭" } },
      { id: "soup", emoji: "🍲", words: { es: "la sopa", ru: "суп", fr: "la soupe", de: "die Suppe", pt: "a sopa", it: "la zuppa", ja: "スープ", zh: "汤" } },
      { id: "banana", emoji: "🍌", words: { es: "el plátano", ru: "банан", fr: "la banane", de: "die Banane", pt: "a banana", it: "la banana", ja: "バナナ", zh: "香蕉" } },
      { id: "tomato", emoji: "🍅", words: { es: "el tomate", ru: "помидор", fr: "la tomate", de: "die Tomate", pt: "o tomate", it: "il pomodoro", ja: "トマト", zh: "西红柿" } },
    ],
  },
  {
    id: "animals",
    emoji: "🐾",
    color: "lime",
    names: { en: "Animals", es: "Animales", ru: "Животные", fr: "Animaux", de: "Tiere", pt: "Animais", it: "Animali", ja: "動物", zh: "动物" },
    items: [
      { id: "dog", emoji: "🐕", words: { es: "el perro", ru: "собака", fr: "le chien", de: "der Hund", pt: "o cachorro", it: "il cane", ja: "犬", zh: "狗" } },
      { id: "cat", emoji: "🐈", words: { es: "el gato", ru: "кошка", fr: "le chat", de: "die Katze", pt: "o gato", it: "il gatto", ja: "猫", zh: "猫" } },
      { id: "bird", emoji: "🐦", words: { es: "el pájaro", ru: "птица", fr: "l'oiseau", de: "der Vogel", pt: "o pássaro", it: "l'uccello", ja: "鳥", zh: "鸟" } },
      { id: "horse", emoji: "🐎", words: { es: "el caballo", ru: "лошадь", fr: "le cheval", de: "das Pferd", pt: "o cavalo", it: "il cavallo", ja: "馬", zh: "马" } },
      { id: "cow", emoji: "🐄", words: { es: "la vaca", ru: "корова", fr: "la vache", de: "die Kuh", pt: "a vaca", it: "la mucca", ja: "牛", zh: "奶牛" } },
      { id: "sheep", emoji: "🐑", words: { es: "la oveja", ru: "овца", fr: "le mouton", de: "das Schaf", pt: "a ovelha", it: "la pecora", ja: "羊", zh: "羊" } },
      { id: "chicken", emoji: "🐔", words: { es: "la gallina", ru: "курица", fr: "la poule", de: "das Huhn", pt: "a galinha", it: "la gallina", ja: "にわとり", zh: "鸡" } },
      { id: "bear", emoji: "🐻", words: { es: "el oso", ru: "медведь", fr: "l'ours", de: "der Bär", pt: "o urso", it: "l'orso", ja: "熊", zh: "熊" } },
      { id: "rabbit", emoji: "🐇", words: { es: "el conejo", ru: "кролик", fr: "le lapin", de: "der Hase", pt: "o coelho", it: "il coniglio", ja: "うさぎ", zh: "兔子" } },
      { id: "mouse", emoji: "🐭", words: { es: "el ratón", ru: "мышь", fr: "la souris", de: "die Maus", pt: "o rato", it: "il topo", ja: "ねずみ", zh: "老鼠" } },
      { id: "frog", emoji: "🐸", words: { es: "la rana", ru: "лягушка", fr: "la grenouille", de: "der Frosch", pt: "o sapo", it: "la rana", ja: "カエル", zh: "青蛙" } },
      { id: "butterfly", emoji: "🦋", words: { es: "la mariposa", ru: "бабочка", fr: "le papillon", de: "der Schmetterling", pt: "a borboleta", it: "la farfalla", ja: "ちょうちょ", zh: "蝴蝶" } },
    ],
  },
  {
    id: "home",
    emoji: "🏠",
    color: "orange",
    names: { en: "Home", es: "Casa", ru: "Дом", fr: "Maison", de: "Zuhause", pt: "Casa", it: "Casa", ja: "家", zh: "家" },
    items: [
      { id: "house", emoji: "🏠", words: { es: "la casa", ru: "дом", fr: "la maison", de: "das Haus", pt: "a casa", it: "la casa", ja: "家", zh: "房子" } },
      { id: "door", emoji: "🚪", words: { es: "la puerta", ru: "дверь", fr: "la porte", de: "die Tür", pt: "a porta", it: "la porta", ja: "ドア", zh: "门" } },
      { id: "window", emoji: "🪟", words: { es: "la ventana", ru: "окно", fr: "la fenêtre", de: "das Fenster", pt: "a janela", it: "la finestra", ja: "窓", zh: "窗户" } },
      { id: "bed", emoji: "🛏️", words: { es: "la cama", ru: "кровать", fr: "le lit", de: "das Bett", pt: "a cama", it: "il letto", ja: "ベッド", zh: "床" } },
      { id: "chair", emoji: "🪑", words: { es: "la silla", ru: "стул", fr: "la chaise", de: "der Stuhl", pt: "a cadeira", it: "la sedia", ja: "椅子", zh: "椅子" } },
      { id: "key", emoji: "🔑", words: { es: "la llave", ru: "ключ", fr: "la clé", de: "der Schlüssel", pt: "a chave", it: "la chiave", ja: "鍵", zh: "钥匙" } },
      { id: "lamp", emoji: "💡", words: { es: "la lámpara", ru: "лампа", fr: "la lampe", de: "die Lampe", pt: "a lâmpada", it: "la lampada", ja: "ランプ", zh: "灯" } },
      { id: "clock", emoji: "🕐", words: { es: "el reloj", ru: "часы", fr: "l'horloge", de: "die Uhr", pt: "o relógio", it: "l'orologio", ja: "時計", zh: "钟" } },
      { id: "book", emoji: "📖", words: { es: "el libro", ru: "книга", fr: "le livre", de: "das Buch", pt: "o livro", it: "il libro", ja: "本", zh: "书" } },
      { id: "phone", emoji: "📱", words: { es: "el teléfono", ru: "телефон", fr: "le téléphone", de: "das Telefon", pt: "o telefone", it: "il telefono", ja: "電話", zh: "手机" } },
      { id: "cup", emoji: "🍵", words: { es: "la taza", ru: "чашка", fr: "la tasse", de: "die Tasse", pt: "a xícara", it: "la tazza", ja: "コップ", zh: "杯子" } },
      { id: "table", emoji: "🪵", words: { es: "la mesa", ru: "стол", fr: "la table", de: "der Tisch", pt: "a mesa", it: "il tavolo", ja: "テーブル", zh: "桌子" } },
    ],
  },
  {
    id: "body",
    emoji: "👋",
    color: "lemon",
    names: { en: "Body", es: "Cuerpo", ru: "Тело", fr: "Corps", de: "Körper", pt: "Corpo", it: "Corpo", ja: "体", zh: "身体" },
    items: [
      { id: "hand", emoji: "✋", words: { es: "la mano", ru: "рука", fr: "la main", de: "die Hand", pt: "a mão", it: "la mano", ja: "手", zh: "手" } },
      { id: "eye", emoji: "👁️", words: { es: "el ojo", ru: "глаз", fr: "l'œil", de: "das Auge", pt: "o olho", it: "l'occhio", ja: "目", zh: "眼睛" } },
      { id: "ear", emoji: "👂", words: { es: "la oreja", ru: "ухо", fr: "l'oreille", de: "das Ohr", pt: "a orelha", it: "l'orecchio", ja: "耳", zh: "耳朵" } },
      { id: "nose", emoji: "👃", words: { es: "la nariz", ru: "нос", fr: "le nez", de: "die Nase", pt: "o nariz", it: "il naso", ja: "鼻", zh: "鼻子" } },
      { id: "mouth", emoji: "👄", words: { es: "la boca", ru: "рот", fr: "la bouche", de: "der Mund", pt: "a boca", it: "la bocca", ja: "口", zh: "嘴巴" } },
      { id: "foot", emoji: "🦶", words: { es: "el pie", ru: "нога", fr: "le pied", de: "der Fuß", pt: "o pé", it: "il piede", ja: "足", zh: "脚" } },
      { id: "head", emoji: "🙂", words: { es: "la cabeza", ru: "голова", fr: "la tête", de: "der Kopf", pt: "a cabeça", it: "la testa", ja: "頭", zh: "头" } },
      { id: "tooth", emoji: "🦷", words: { es: "el diente", ru: "зуб", fr: "la dent", de: "der Zahn", pt: "o dente", it: "il dente", ja: "歯", zh: "牙齿" } },
      { id: "hair", emoji: "💇", words: { es: "el pelo", ru: "волосы", fr: "les cheveux", de: "die Haare", pt: "o cabelo", it: "i capelli", ja: "髪", zh: "头发" } },
      { id: "heart", emoji: "❤️", words: { es: "el corazón", ru: "сердце", fr: "le cœur", de: "das Herz", pt: "o coração", it: "il cuore", ja: "心臓", zh: "心脏" } },
    ],
  },
  {
    id: "traveling",
    emoji: "✈️",
    color: "orange",
    names: { en: "Traveling", es: "Viajes", ru: "Путешествия", fr: "Voyages", de: "Reisen", pt: "Viagens", it: "Viaggi", ja: "旅行", zh: "旅行" },
    items: [
      { id: "car", emoji: "🚗", words: { es: "el coche", ru: "машина", fr: "la voiture", de: "das Auto", pt: "o carro", it: "la macchina", ja: "車", zh: "汽车" } },
      { id: "bus", emoji: "🚌", words: { es: "el autobús", ru: "автобус", fr: "le bus", de: "der Bus", pt: "o ônibus", it: "l'autobus", ja: "バス", zh: "公交车" } },
      { id: "train", emoji: "🚆", words: { es: "el tren", ru: "поезд", fr: "le train", de: "der Zug", pt: "o trem", it: "il treno", ja: "電車", zh: "火车" } },
      { id: "plane", emoji: "✈️", words: { es: "el avión", ru: "самолёт", fr: "l'avion", de: "das Flugzeug", pt: "o avião", it: "l'aereo", ja: "飛行機", zh: "飞机" } },
      { id: "bicycle", emoji: "🚲", words: { es: "la bicicleta", ru: "велосипед", fr: "le vélo", de: "das Fahrrad", pt: "a bicicleta", it: "la bicicletta", ja: "自転車", zh: "自行车" } },
      { id: "boat", emoji: "⛵", words: { es: "el barco", ru: "лодка", fr: "le bateau", de: "das Boot", pt: "o barco", it: "la barca", ja: "船", zh: "船" } },
      { id: "map", emoji: "🗺️", words: { es: "el mapa", ru: "карта", fr: "la carte", de: "die Karte", pt: "o mapa", it: "la mappa", ja: "地図", zh: "地图" } },
      { id: "suitcase", emoji: "🧳", words: { es: "la maleta", ru: "чемодан", fr: "la valise", de: "der Koffer", pt: "a mala", it: "la valigia", ja: "スーツケース", zh: "行李箱" } },
      { id: "ticket", emoji: "🎫", words: { es: "el billete", ru: "билет", fr: "le billet", de: "die Fahrkarte", pt: "o bilhete", it: "il biglietto", ja: "切符", zh: "票" } },
      { id: "road", emoji: "🛣️", words: { es: "la carretera", ru: "дорога", fr: "la route", de: "die Straße", pt: "a estrada", it: "la strada", ja: "道", zh: "路" } },
    ],
  },
  {
    id: "family",
    emoji: "👨‍👩‍👧",
    color: "violet",
    names: { en: "Family", es: "Familia", ru: "Семья", fr: "Famille", de: "Familie", pt: "Família", it: "Famiglia", ja: "家族", zh: "家庭" },
    items: [
      { id: "mother", emoji: "👩", words: { es: "la madre", ru: "мама", fr: "la mère", de: "die Mutter", pt: "a mãe", it: "la madre", ja: "お母さん", zh: "妈妈" } },
      { id: "father", emoji: "👨", words: { es: "el padre", ru: "папа", fr: "le père", de: "der Vater", pt: "o pai", it: "il padre", ja: "お父さん", zh: "爸爸" } },
      { id: "baby", emoji: "👶", words: { es: "el bebé", ru: "малыш", fr: "le bébé", de: "das Baby", pt: "o bebê", it: "il bambino", ja: "赤ちゃん", zh: "宝宝" } },
      { id: "grandma", emoji: "👵", words: { es: "la abuela", ru: "бабушка", fr: "la grand-mère", de: "die Oma", pt: "a avó", it: "la nonna", ja: "おばあちゃん", zh: "奶奶" } },
      { id: "grandpa", emoji: "👴", words: { es: "el abuelo", ru: "дедушка", fr: "le grand-père", de: "der Opa", pt: "o avô", it: "il nonno", ja: "おじいちゃん", zh: "爷爷" } },
      { id: "boy", emoji: "👦", words: { es: "el niño", ru: "мальчик", fr: "le garçon", de: "der Junge", pt: "o menino", it: "il ragazzo", ja: "男の子", zh: "男孩" } },
      { id: "girl", emoji: "👧", words: { es: "la niña", ru: "девочка", fr: "la fille", de: "das Mädchen", pt: "a menina", it: "la ragazza", ja: "女の子", zh: "女孩" } },
      { id: "friends", emoji: "🧑‍🤝‍🧑", words: { es: "los amigos", ru: "друзья", fr: "les amis", de: "die Freunde", pt: "os amigos", it: "gli amici", ja: "友達", zh: "朋友" } },
    ],
  },
  {
    id: "sport",
    emoji: "⚽",
    color: "lime",
    names: { en: "Sport", es: "Deporte", ru: "Спорт", fr: "Sport", de: "Sport", pt: "Esporte", it: "Sport", ja: "スポーツ", zh: "运动" },
    items: [
      { id: "ball", emoji: "⚽", words: { es: "el balón", ru: "мяч", fr: "le ballon", de: "der Ball", pt: "a bola", it: "il pallone", ja: "ボール", zh: "球" } },
      { id: "run", emoji: "🏃", words: { es: "correr", ru: "бегать", fr: "courir", de: "laufen", pt: "correr", it: "correre", ja: "走る", zh: "跑步" } },
      { id: "swim", emoji: "🏊", words: { es: "nadar", ru: "плавать", fr: "nager", de: "schwimmen", pt: "nadar", it: "nuotare", ja: "泳ぐ", zh: "游泳" } },
      { id: "jump", emoji: "🤸", words: { es: "saltar", ru: "прыгать", fr: "sauter", de: "springen", pt: "pular", it: "saltare", ja: "跳ぶ", zh: "跳" } },
      { id: "dance", emoji: "💃", words: { es: "bailar", ru: "танцевать", fr: "danser", de: "tanzen", pt: "dançar", it: "ballare", ja: "踊る", zh: "跳舞" } },
      { id: "basketball", emoji: "🏀", words: { es: "el baloncesto", ru: "баскетбол", fr: "le basket", de: "der Basketball", pt: "o basquete", it: "il basket", ja: "バスケ", zh: "篮球" } },
      { id: "tennis", emoji: "🎾", words: { es: "el tenis", ru: "теннис", fr: "le tennis", de: "das Tennis", pt: "o tênis", it: "il tennis", ja: "テニス", zh: "网球" } },
      { id: "ski", emoji: "⛷️", words: { es: "esquiar", ru: "кататься на лыжах", fr: "skier", de: "Ski fahren", pt: "esquiar", it: "sciare", ja: "スキー", zh: "滑雪" } },
    ],
  },
  {
    id: "health",
    emoji: "🩺",
    color: "coral",
    names: { en: "Health", es: "Salud", ru: "Здоровье", fr: "Santé", de: "Gesundheit", pt: "Saúde", it: "Salute", ja: "健康", zh: "健康" },
    items: [
      { id: "doctor", emoji: "🧑‍⚕️", words: { es: "el médico", ru: "врач", fr: "le médecin", de: "der Arzt", pt: "o médico", it: "il medico", ja: "お医者さん", zh: "医生" } },
      { id: "medicine", emoji: "💊", words: { es: "la medicina", ru: "лекарство", fr: "le médicament", de: "die Medizin", pt: "o remédio", it: "la medicina", ja: "薬", zh: "药" } },
      { id: "hospital", emoji: "🏥", words: { es: "el hospital", ru: "больница", fr: "l'hôpital", de: "das Krankenhaus", pt: "o hospital", it: "l'ospedale", ja: "病院", zh: "医院" } },
      { id: "sleep", emoji: "😴", words: { es: "dormir", ru: "спать", fr: "dormir", de: "schlafen", pt: "dormir", it: "dormire", ja: "寝る", zh: "睡觉" } },
      { id: "eat", emoji: "🍽️", words: { es: "comer", ru: "есть", fr: "manger", de: "essen", pt: "comer", it: "mangiare", ja: "食べる", zh: "吃饭" } },
      { id: "drink", emoji: "🥤", words: { es: "beber", ru: "пить", fr: "boire", de: "trinken", pt: "beber", it: "bere", ja: "飲む", zh: "喝" } },
      { id: "wash", emoji: "🧼", words: { es: "lavar", ru: "мыть", fr: "laver", de: "waschen", pt: "lavar", it: "lavare", ja: "洗う", zh: "洗" } },
      { id: "tooth-brush", emoji: "🪥", words: { es: "el cepillo", ru: "зубная щётка", fr: "la brosse à dents", de: "die Zahnbürste", pt: "a escova", it: "lo spazzolino", ja: "歯ブラシ", zh: "牙刷" } },
    ],
  },
  {
    id: "nature",
    emoji: "🌳",
    color: "mint",
    names: { en: "Nature", es: "Naturaleza", ru: "Природа", fr: "Nature", de: "Natur", pt: "Natureza", it: "Natura", ja: "自然", zh: "自然" },
    items: [
      { id: "sun", emoji: "☀️", words: { es: "el sol", ru: "солнце", fr: "le soleil", de: "die Sonne", pt: "o sol", it: "il sole", ja: "太陽", zh: "太阳" } },
      { id: "moon", emoji: "🌙", words: { es: "la luna", ru: "луна", fr: "la lune", de: "der Mond", pt: "a lua", it: "la luna", ja: "月", zh: "月亮" } },
      { id: "tree", emoji: "🌳", words: { es: "el árbol", ru: "дерево", fr: "l'arbre", de: "der Baum", pt: "a árvore", it: "l'albero", ja: "木", zh: "树" } },
      { id: "flower", emoji: "🌸", words: { es: "la flor", ru: "цветок", fr: "la fleur", de: "die Blume", pt: "a flor", it: "il fiore", ja: "花", zh: "花" } },
      { id: "rain", emoji: "🌧️", words: { es: "la lluvia", ru: "дождь", fr: "la pluie", de: "der Regen", pt: "a chuva", it: "la pioggia", ja: "雨", zh: "雨" } },
      { id: "snow", emoji: "❄️", words: { es: "la nieve", ru: "снег", fr: "la neige", de: "der Schnee", pt: "a neve", it: "la neve", ja: "雪", zh: "雪" } },
      { id: "mountain", emoji: "⛰️", words: { es: "la montaña", ru: "гора", fr: "la montagne", de: "der Berg", pt: "a montanha", it: "la montagna", ja: "山", zh: "山" } },
      { id: "sea", emoji: "🌊", words: { es: "el mar", ru: "море", fr: "la mer", de: "das Meer", pt: "o mar", it: "il mare", ja: "海", zh: "大海" } },
      { id: "fire", emoji: "🔥", words: { es: "el fuego", ru: "огонь", fr: "le feu", de: "das Feuer", pt: "o fogo", it: "il fuoco", ja: "火", zh: "火" } },
      { id: "star", emoji: "⭐", words: { es: "la estrella", ru: "звезда", fr: "l'étoile", de: "der Stern", pt: "a estrela", it: "la stella", ja: "星", zh: "星星" } },
    ],
  },
  {
    id: "work",
    emoji: "💼",
    color: "violet",
    names: { en: "Work", es: "Trabajo", ru: "Работа", fr: "Travail", de: "Arbeit", pt: "Trabalho", it: "Lavoro", ja: "仕事", zh: "工作" },
    items: [
      { id: "computer", emoji: "💻", words: { es: "el ordenador", ru: "компьютер", fr: "l'ordinateur", de: "der Computer", pt: "o computador", it: "il computer", ja: "パソコン", zh: "电脑" } },
      { id: "pen", emoji: "🖊️", words: { es: "el bolígrafo", ru: "ручка", fr: "le stylo", de: "der Stift", pt: "a caneta", it: "la penna", ja: "ペン", zh: "笔" } },
      { id: "paper", emoji: "📄", words: { es: "el papel", ru: "бумага", fr: "le papier", de: "das Papier", pt: "o papel", it: "la carta", ja: "紙", zh: "纸" } },
      { id: "money", emoji: "💰", words: { es: "el dinero", ru: "деньги", fr: "l'argent", de: "das Geld", pt: "o dinheiro", it: "i soldi", ja: "お金", zh: "钱" } },
      { id: "teacher", emoji: "🧑‍🏫", words: { es: "el profesor", ru: "учитель", fr: "le professeur", de: "der Lehrer", pt: "o professor", it: "l'insegnante", ja: "先生", zh: "老师" } },
      { id: "farmer", emoji: "🧑‍🌾", words: { es: "el agricultor", ru: "фермер", fr: "le fermier", de: "der Bauer", pt: "o agricultor", it: "il contadino", ja: "農家", zh: "农民" } },
      { id: "cook", emoji: "🧑‍🍳", words: { es: "el cocinero", ru: "повар", fr: "le cuisinier", de: "der Koch", pt: "o cozinheiro", it: "il cuoco", ja: "コックさん", zh: "厨师" } },
      { id: "shop", emoji: "🏪", words: { es: "la tienda", ru: "магазин", fr: "le magasin", de: "der Laden", pt: "a loja", it: "il negozio", ja: "お店", zh: "商店" } },
    ],
  },
];

export const domainById = (id: string) => VOCAB_DOMAINS.find((d) => d.id === id);

/** TPR-style action commands for the listening trainer (Phase 1 "Total Physical Response") */
export const TPR_COMMANDS: { id: string; emoji: string; words: Partial<Record<string, string>> }[] = [
  { id: "stand", emoji: "🧍", words: { es: "¡Levántate!", ru: "Встань!", fr: "Lève-toi !", de: "Steh auf!", pt: "Levanta-te!", it: "Alzati!", ja: "立って！", zh: "站起来！" } },
  { id: "sit", emoji: "🪑", words: { es: "¡Siéntate!", ru: "Сядь!", fr: "Assieds-toi !", de: "Setz dich!", pt: "Senta-te!", it: "Siediti!", ja: "座って！", zh: "坐下！" } },
  { id: "point", emoji: "👉", words: { es: "¡Señala!", ru: "Покажи!", fr: "Montre !", de: "Zeig!", pt: "Aponta!", it: "Indica!", ja: "指さして！", zh: "指一指！" } },
  { id: "take", emoji: "🤲", words: { es: "¡Toma!", ru: "Возьми!", fr: "Prends !", de: "Nimm!", pt: "Pega!", it: "Prendi!", ja: "取って！", zh: "拿着！" } },
  { id: "give", emoji: "🫴", words: { es: "¡Dame!", ru: "Дай!", fr: "Donne !", de: "Gib!", pt: "Dá!", it: "Dammi!", ja: "ちょうだい！", zh: "给我！" } },
  { id: "open", emoji: "📂", words: { es: "¡Abre!", ru: "Открой!", fr: "Ouvre !", de: "Öffne!", pt: "Abre!", it: "Apri!", ja: "開けて！", zh: "打开！" } },
  { id: "close", emoji: "📁", words: { es: "¡Cierra!", ru: "Закрой!", fr: "Ferme !", de: "Schließ!", pt: "Fecha!", it: "Chiudi!", ja: "閉めて！", zh: "关上！" } },
  { id: "walk", emoji: "🚶", words: { es: "¡Camina!", ru: "Иди!", fr: "Marche !", de: "Geh!", pt: "Anda!", it: "Cammina!", ja: "歩いて！", zh: "走！" } },
];
